### ISSUE TITLE
Walking instead of sprinting feels slower in 1.13.x than in other versions.

### ISSUE THREAD

**Issue by Kichura** [Earthcomputer/multiconnect#104]
When joining any server that is on 1.13.x; Walking instead of sprinting (or doing anything else) will make the player movement feel like you're moving slightly slower than expected via 1.12.x and other versions.

How to reproduce:

1: Play on any server that supports 1.13.x clients,
2: Try to walk anywhere you want and then basically compare it with another version using multiconnect itself.

**Comment by Earthcomputer** [comment]
Cannot reproduce. I tested a real 1.13.2 client against a multiconnect client on a 1.13.2 server, they took 23.66 and 23.64 seconds respectively to travel the same 101 blocks, within the margin of error.

**Comment by Kichura** [comment]
Tried lowering the FOV to normal instead of Quake Pro; The speed feels fine again because of human eye-sight.

In short = Issue is invalid.
