### ISSUE TITLE
Errors while trying to connect to custom server (node-minecraft-protocol)

### ISSUE THREAD

**Issue by Patbox** [Earthcomputer/multiconnect#105]
I tried MultiConnect (on 1.16.3) with custom server using node-minecraft-protocol (1.16.1) as a base and got this error.
![image](https://user-images.githubusercontent.com/39821509/95125493-5c794c80-0755-11eb-9134-6a0b87f79a00.png)
Vanilla 1.16.1 works just fine with it

Log: https://gist.github.com/Patbox/370316b0d158ec268fd6016a8dcfe0e4

Server: `pb4.eu:25566`
Server software: 
- [VoxelSrv-Server](https://github.com/VoxelSrv/voxelsrv-server)
- [MConnect (plugin for Minecraft protocol)](https://github.com/VoxelSrv/server-plugins/)
- [MC Protocol Lib I used (with selected version 1.16.1):](https://github.com/PrismarineJS/node-minecraft-protocol)

**Comment by Earthcomputer** [comment]
Oh no, it's *that* code... I was wondering when that would break on someone...
