### ISSUE TITLE
Failure to connect to 1.16.3 server on 1.16.2.

### ISSUE THREAD

**Issue by uwuplant** [Earthcomputer/multiconnect#108]
I'm using the latest fabric loader version, and latest multiconnect release. No other mods are being used.

https://hastebin.com/ulibogaxer - MC log

**Comment by Earthcomputer** [comment]
The latest version of multiconnect is not compatible with 1.16.2. Please upgrade your client, most other mods should work.

**Comment by uwuplant** [comment]
oh, sorry for making pointless issue then :/
