### ISSUE TITLE
Global toggle

### ISSUE THREAD

**Issue by Madis0** [Earthcomputer/multiconnect#115]
Are there any plans to implement a global toggle for the mod?
That could come useful in:

- modpacks, to add the mod but make it opt-in
- seeing how many servers are actually compatible
- quick testing in the case of some problem to see if this mod is the cause

Suggested way: a button on top of the server list similar to the current per-server one.

**Comment by Earthcomputer** [comment]
> modpacks, to add the mod but make it opt-in

What? Just disable the mod if you don't want it.

> seeing how many servers are actually compatible

With what? Compatible means you can connect to them.

> quick testing in the case of some problem to see if this mod is the cause

Again, modpack creators have tools to do that. Do you use multimc? You can disable mods by unchecking a checkbox.

**Comment by Madis0** [comment]
Actually I was thinking about Twitch launcher, but fair enough, maybe the Curseforge launcher will improve the optional mod UX.

> With what? Compatible means you can connect to them.

Compatible with the actual client version.

**Comment by Earthcomputer** [comment]
Why would you want to check if all servers at once are compatible with the actual client version if you have multiconnect to connect to them? I can see people wanting to do this for individual servers, in which case you already have the option to override for individual servers.
In fact, that is also an answer to your third bullet point. If you want to diagnose a problem on a particular server you can already change the version you connect with.

**Comment by CDAGaming** [comment]
@Madis0 I have support for this in my fork at this time, but It's Earths call whether or not it has a usage in multiconnect that isn't already covered by the supported per-server dropdown

**Comment by Madis0** [comment]
> I have support for this in my fork at this time

Tested that out and I like that implementation. 

> Why would you want to check if all servers at once are compatible with the actual client version if you have multiconnect to connect to them? 

One reason could be that multiconnect by default displays the server list the same way the running client does, meaning the user cannot see the compatibility per-version as easily, unless they change and test all servers individually. 

For example, an 1.12.2 user wants to play the same servers as a 1.16.3 user (which is possible because of ViaVersion), but the 1.16.3 user does not have an easy way of telling which servers they can play unless they test them one by one.

**Comment by Earthcomputer** [comment]
I have rejected this feature on more than one occasion. It hides the more useful feature of tweaking servers individually, when players see the global toggle they think that is the only option.
Your problem is valid, however your proposed solution isn't the only one possible and it's not one I'm prepared to go for. Something I would be prepared to go for is more along the lines of your older request, #24, which I want to implement, there are just a few technical hurdles along the way (and some higher priority tasks).

**Comment by CDAGaming** [comment]
@Earthcomputer Actually, #24 is pretty feasable to acheive. I can attempt this likely later this week hopefully.

**Comment by Earthcomputer** [comment]
That would be great! You have just got to beware of ViaFabric compatibility.
