### ISSUE TITLE
Some servers won't load in the text on signs.

### ISSUE THREAD

**Issue by Wxrlds** [Earthcomputer/multiconnect#118]
(This is mostly copy paste from the Discord Server. [Link](https://discord.com/channels/703363189081112647/703364312915509249/769975209868132372))

I think I found a bug that's specific to the servers which don't support the version 1.16.3.
Signs don't always load their text.

``play.timolia.de`` only supports 1.8-1.15.2 and ``tumira.net`` supports 1.8-1.16.2.

This happens with ``Minecraft 1.16.3``, ``multiconnect-1.3.30`` and ``Fabric 0.9.3 build 207`` as well as with ``Fabric 0.10.3 build 211 (currently most recent version)``.

I tried joining the servers with multiconnect using various versions and it still happens.
When joining the servers with Vanilla 1.12.2 this does *not* happen.
On other servers this doesn't happen (most of the servers I have in my list support 1.16.3 so I'm not really sure if there are exceptions).
Removing the texture pack also didn't fix the issue.

On ``Rewinside.tv`` (supports 1.8-1.12.2) this does *not* happen.

Signs on Timolia not loading in. (On Tumira there only seem to be two easy reachable signs located under bedwars)
![Image](https://cdn.discordapp.com/attachments/703364312915509249/769975209603235890/unknown.png)

Joining Tumira and Timolia with vanilla 1.15.2 loads the signs correctly.

On a vanilla 1.16.2 server signs load correctly.

Timolia and Tumira both seem to use BungeeCord and Paper.
What Timolia uses:
![Image](https://cdn.discordapp.com/attachments/703364312915509249/769982306210283550/unknown.png)
What Tumira uses:
![Image](https://cdn.discordapp.com/attachments/703364312915509249/769982351340994590/unknown.png)

**Comment by Finoway** [comment]
Hello, is there any news to bug? (I admit it would be nice not to have it)

**Comment by Earthcomputer** [comment]
It's priority medium which means it will be fixed in the next wave of bugfixes.

**Comment by Earthcomputer** [comment]
Timolia seems to be down, I can't find bedwars on Tumira

**Comment by Wxrlds** [comment]
Seems like Tumira removed Bedwars.
Anyway, both Timolia and Tumira updated to 1.16.5 and I haven't observed this issue ever since.
Timolia being offline is something I've seen regularly when it's in the server list but when I attempt to connect to it, I can join just fine. Not sure if this could be a multiconnect issue or not, as it doesn't happen always. This might have something to that that most of the time when connecting to Timolia it says failed to request version.
Maybe @Finoway can share on which server they've experienced this issue.

**Comment by Finoway** [comment]
> Seems like Tumira removed Bedwars.
> Anyway, both Timolia and Tumira updated to 1.16.5 and I haven't observed this issue ever since.
> Timolia being offline is something I've seen regularly when it's in the server list but when I attempt to connect to it, I can join just fine. Not sure if this could be a multiconnect issue or not, as it doesn't happen always. This might have something to that that most of the time when connecting to Timolia it says failed to request version.
> Maybe @Finoway can share on which server they've experienced this issue.

Hi, The only server I can remember where I encountered this bug was on funcraft.net when I first got into the FreeCube I went to the players' plots and I noticed that the signs were randomly empty

**Comment by Finoway** [comment]
> > Seems like Tumira removed Bedwars.
> > Anyway, both Timolia and Tumira updated to 1.16.5 and I haven't observed this issue ever since.
> > Timolia being offline is something I've seen regularly when it's in the server list but when I attempt to connect to it, I can join just fine. Not sure if this could be a multiconnect issue or not, as it doesn't happen always. This might have something to that that most of the time when connecting to Timolia it says failed to request version.
> > Maybe @Finoway can share on which server they've experienced this issue.
> 
> Hi, The only server I can remember where I encountered this bug was on funcraft.net when I first got into the FreeCube I went to the players' plots and I noticed that the signs were randomly empty

I tried on funcraft in 1.17.1 to 1.11.2 the problem seems to be fixed 

![image](https://user-images.githubusercontent.com/48923336/125136908-f79bba00-e10b-11eb-87dc-72ef662c7ab6.png)

**Comment by Earthcomputer** [comment]
Presuming this is fixed
