### ISSUE TITLE
Structure voids show up as unrelated blocks lower than 1.10 on ViaBackwards servers

### ISSUE THREAD

**Issue by mygizli04** [Earthcomputer/multiconnect#128]
This is what it should look like ( from 1.10 multiconnect )
![1.10](https://user-images.githubusercontent.com/42012824/98680655-26923e00-237b-11eb-9de6-b3547ba1c358.png)

This is what it looks like in 1.9 multiconnect
![1.9](https://user-images.githubusercontent.com/42012824/98680698-3742b400-237b-11eb-98f9-a0e2bdf23d61.png)

And even though it's in the 1.8 branch, this is what it looks like with 1.8 multiconnect
![1.8](https://user-images.githubusercontent.com/42012824/98680796-517c9200-237b-11eb-9ca0-c9652d053771.png)

This is what it looks like in vanilla 1.9/1.8
![vanilla](https://user-images.githubusercontent.com/42012824/98680832-622d0800-237b-11eb-8f4f-3ec24a9895a0.png)

Tested on minehut. I imagined it'd be a problem with viaversion but i couldn't reproduce with paper using viaversion.

**Comment by Earthcomputer** [comment]
What block is that? That looks like air in vanilla, not flowing water

**Comment by ehylo** [comment]
![gggggg](https://user-images.githubusercontent.com/48396713/98709230-f7f27400-2336-11eb-8a72-624671079041.png)
Seems to be the structure void block

**Comment by Earthcomputer** [comment]
What is it in vanilla 1.9 and below? The structure void block was introduced in 1.10

**Comment by ehylo** [comment]
It doesn't show as anything just the block behind it, although I don't think the server is 1.8.9 because if I do /version it tells me its using version 1.16.4 so it might be using ViaBackwards

**Comment by mygizli04** [comment]
If you do /plugins it shows you that it uses the 3 via plugins ( i believe forks )

**Comment by Earthcomputer** [comment]
If I were to guess, if a 1.9/1.8 client is presented with chunk data containing blocks it doesn't understand, it replaces them with air. So ViaBackwards relies on this behaviour and leaves structure voids untranslated. However when multiconnect receives blocks that the server shouldn't recognize, that is treated like undefined behaviour, hence what you're seeing.

**Comment by Earthcomputer** [comment]
The question now is whether multiconnect is wrong to treat this as undefined behaviour, or whether ViaBackwards is wrong not to sanitize this data.

**Comment by Earthcomputer** [comment]
Just looked at the ViaBackwards code, it seems to map structure voids to block ID 287 for some reason, but that block ID doesn't exist, so my hypothesis was almost right.
