### ISSUE TITLE
Custom payloads broken for other mods

### ISSUE THREAD

**Issue by kosma** [Earthcomputer/multiconnect#130]
With Multiconnect enabled, all other mods I have installed no longer receive custom payload packets.

Affected mod combinations in my setup:

Servux (server) + Minihud (client) - structure bounding boxes not showing
WorldNamePacket (server) + VoxelMap (client) - world name packet not received by VoxelMap

**Comment by Earthcomputer** [comment]
This is intentional. I made a whole API to get around this. Use it.

**Comment by kosma** [comment]
Thanks for the explanation, I didn't think about this scenario. I only now realized it works correctly when the version matches, so it's not as a big problem as I thought.
