### ISSUE TITLE
trying to log in to a 1.12.2 server with a 1.16 client doesn't work

### ISSUE THREAD

**Issue by Itssunnyk8** [Earthcomputer/multiconnect#132]
i tried to log into a 1.12.2 world in a 1.16 client and it will load the world for a minute and then just disconnect me
i tried to multiconnect into other 1.12.2 server and it did work its only on that server the server is using carpet as far as i know thats the only mod

**Comment by Earthcomputer** [comment]
Please send the log

**Comment by Itssunnyk8** [comment]
by log you mean server log or the message i get when i get disconencted?

**Comment by Earthcomputer** [comment]
If you have access to the server log that'd be great, but I meant the client log. And the message you get when you're disconnected may help. You need to learn to give as much info as possible in bug reports, how do you expect me to solve a problem where all you say is "it doesn't work", when I've tried countless times and it does.

**Comment by Itssunnyk8** [comment]
so it shows at server logs ([15:08:37] [Server thread/INFO]: itssunnyk lost connection: Timed out
[15:08:37] [Server thread/INFO]: itssunnyk left the game) and it only shows that when i use the 1.16.4 multiconnect client (or any 1.16 client) as it shows my ping is just very high whenever i log in to the server, but for some weird reason i can't find an explanation to when i use a 1.12.2 client it works fine, sometimes i did manage to get in though, very rarely.

**Comment by Earthcomputer** [comment]
What did I literally just fucking tell you to do? SEND THE CLIENT LOG

**Comment by Itssunnyk8** [comment]
i am sorry earth but im dumb it just says "disconnected" and sometimes it says "timed out" (earth im so sorry for wasting your time with my dumb answers, i hope this is the answer u want, and if its not that you will have to tell me what a client log is)

**Comment by Earthcomputer** [comment]
Send me the "latest.log" file inside your ".minecraft/logs" folder.

**Comment by Itssunnyk8** [comment]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/5618193/latest.log)
 i believe its that

**Comment by Earthcomputer** [comment]
Hmm, it's hard to tell what's going on from that log. Can you send a screenshot with a vanilla client of your surroundings on the server at the location you are getting kicked with multiconnect?

**Comment by Itssunnyk8** [comment]
![2020-11-30_21 27 22](https://user-images.githubusercontent.com/75048522/100654809-0be82f00-3353-11eb-8c1a-9f3ba30189e9.png)
![2020-11-30_21 27 24](https://user-images.githubusercontent.com/75048522/100654831-130f3d00-3353-11eb-85ae-60a0241be05c.png)
![2020-11-30_21 27 25](https://user-images.githubusercontent.com/75048522/100654843-15719700-3353-11eb-8184-f507b2f03012.png)
![2020-11-30_21 27 26](https://user-images.githubusercontent.com/75048522/100654850-17d3f100-3353-11eb-8dd2-7d904e258aed.png)
![2020-11-30_21 27 27](https://user-images.githubusercontent.com/75048522/100654856-19051e00-3353-11eb-99bf-386893ab6b8e.png)
![2020-11-30_21 27 28](https://user-images.githubusercontent.com/75048522/100654861-1c98a500-3353-11eb-8094-6b3162d127fe.png)
![2020-11-30_21 27 32](https://user-images.githubusercontent.com/75048522/100654873-202c2c00-3353-11eb-9e30-cec41d11b9cc.png)

**Comment by Earthcomputer** [comment]
There is nothing unusual in those screenshots, this doesn't happen to anyone else, I'm going to have to assume that these are connection issues you get in vanilla too.
