### ISSUE TITLE
[1.16.4] Weird rendering engine behavior when connecting to server with version below 1.16.4

### ISSUE THREAD

**Issue by bG9sIHVyIGhvbW8** [Earthcomputer/multiconnect#135]
Hi,

I am connecting to a 1.12.2 MC server with said version, and I noticed that the rendering engine is behaving weirdly;

I placed down this sign, and when going into another world and back (or rejoining the server), it stopped rendering properly:

![image](https://user-images.githubusercontent.com/4199643/102943339-b7356100-4485-11eb-9bf7-efdfd5a2a5ea.png)
![image](https://user-images.githubusercontent.com/4199643/102943356-c0bec900-4485-11eb-971f-cdca287a028c.png)

Additionally, the lighting engine behaves in very weird ways when Sodium is present (and I'm still connecting with 1.12.2):

![image](https://user-images.githubusercontent.com/4199643/102943229-7c332d80-4485-11eb-82e1-8e1085f6a152.png)

I'm using Fabric Loader 0.10.8 1.16.4.

**Comment by Earthcomputer** [comment]
Can you reproduce this with *only* multiconnect (no Sodium etc) installed? The lighting issue is a known Sodium issue, so should not be reported here.

**Comment by bG9sIHVyIGhvbW8** [comment]
Yes, the weird sign behavior does in fact still occur with only multiconnect installed. 

As for the lighting issue, it only happens when connecting with a different version other than the native client version, so I wasn't sure if multiconnect or Sodium was at fault.

**Comment by obj-obj** [comment]
Multiconnect is mapping the sign to `minecraft:wall_sign` instead of `minecraft:oak_sign`

**Comment by Earthcomputer** [comment]
@obj-obj please don't hijack other issues with your issue

**Comment by obj-obj** [comment]
@Earthcomputer I meant that I think that's why the signs aren't rendering

**Comment by Earthcomputer** [comment]
Yes but it's what I think caused it that matters

**Comment by obj-obj** [comment]
I was just trying to help a bit...

**Comment by Earthcomputer** [comment]
Does this still occur on the latest version?

**Comment by obj-obj** [comment]
Will test tomorrow
