### ISSUE TITLE
Attempted to register ID at different raw IDs

### ISSUE THREAD

**Issue by yts233** [Earthcomputer/multiconnect#136]
![2021-01-12 20-39-19 的屏幕截图](https://user-images.githubusercontent.com/62997025/104315784-707fd780-5516-11eb-8a63-a2af81c21714.png)

**Comment by Earthcomputer** [comment]
What version of multiconnect are you using? This was fixed several versions ago

**Comment by yts233** [comment]
It's 1.3.34 for 1.16.4

**Comment by Earthcomputer** [comment]
Related internally to #125, I think

**Comment by Earthcomputer** [comment]
Giving it a low priority because it's proven hard to diagnose and can be fixed by restarting your client. If this is wrong please let me know.

**Comment by yts233** [comment]
I just removed the carpetmod(fabric-carpet-1.16.4-1.4.20+v201202.jar) and it did work

**Comment by yts233** [comment]
It may be carpet mod interference

**Comment by HyeN2018** [comment]
Im attempting to connect to 9b9t.org. The client version is 1.17.1 and the server is 1.12.2, there are no other mods or textures, just multiconnect and forge

**Comment by HyeN2018** [comment]
@Earthcomputer, could you take a look ^^
I made a bit of testing and I get those errors as in yts233's image and after some retries, I can get into the server but it's still annoying because sometimes it crashes after some retries. To join the server can take up to 10 minutes...
