### ISSUE TITLE
[1.12.2] Scoreboard colors are wrong

### ISSUE THREAD

**Issue by RaphiMC** [Earthcomputer/multiconnect#139]
Used multiconnect version: 1.3.34 for 1.16.4
Servers native version is 1.8
Used protocol version in multiconnect: 1.12.2 (Video compares to 1.12.2 client)
Server: MineSucht.net
Steps to reproduce: Watch the video

Issue: The scoreboard has the wrong colors (can be seen at 00:24). Maybe related to #133 

Video that shows all the bugs: https://streamable.com/yfiy3r

**Comment by SkyWors** [comment]
Hey! This server probably uses hexadecimal colours, 1.16 is the only version of minecraft that knows these colours.

**Comment by Earthcomputer** [comment]
This server is down now

**Comment by RaphiMC** [comment]
The server works for me

**Comment by TheGameratorT** [comment]
This issue happens on CubeCraft `play.cubecraft.net` when connecting from 1.18 to 1.12.2, I can try to find a solution.
