### ISSUE TITLE
Failed to request server protocol version

### ISSUE THREAD

**Issue by assasin541** [Earthcomputer/multiconnect#142]
![image](https://user-images.githubusercontent.com/59084765/104821417-03cd4b80-583c-11eb-8d8d-df1af5cdb9cf.png)

**Comment by Earthcomputer** [comment]
Yeah that's the server's fault

**Comment by assasin541** [comment]
@Earthcomputer how?

**Comment by Earthcomputer** [comment]
How do you expect me to know? Maybe if you give me the slightest amount of information about the server you are connecting to i might be able to help.
