### ISSUE TITLE
[1.11 -> 1.10] Flower pot causes client/server block desync

### ISSUE THREAD

**Issue by RaphiMC** [Earthcomputer/multiconnect#145]
Used multiconnect version: 1.3.34 for 1.16.4
Servers native version is 1.8

1.11 Added a feature that allows the player to take the flower out of a flower pot. This is not possible in 1.10 -> Trying to take out a flower with multiconnect on a <=1.10 server causes the block to desync and sometimes inventory also desyncs.
The solution would be to cancel the action.

**Comment by Earthcomputer** [comment]
Oh, lol
https://github.com/Earthcomputer/multiconnect/blob/c1673b3c173c8abff6d5e6d79600bc043b0897a8/src/main/java/net/earthcomputer/multiconnect/protocols/v1_10/mixin/MixinFlowerPotBlock.java#L23

**Comment by RaphiMC** [comment]
I didn't even see that TODO, but I also tried it myself in my own mod and it didn't work there neither (I also injected into FlowerPotBlock), maybe its handled somewhere else.

**Comment by Earthcomputer** [comment]
![Peek 2021-05-30 23-32](https://user-images.githubusercontent.com/13084089/120122203-55e58c80-c19f-11eb-8e18-ef537f38f792.gif)

That seems to be the real cause
