### ISSUE TITLE
Connection drops when teleporting to a new dimension (21w03a)

### ISSUE THREAD

**Issue by Kichura** [Earthcomputer/multiconnect#148]
When teleporting to a new dimension using multiverse or another related plugin, Multiconnect does not seem to accept the bungeecord/multiverse world and drops the connection instead right before the player can see anything on where they even are now at.

This issue also applies to hypixel when warping to a new bungeecord server of any kind.

**Comment by Jordin** [comment]
I believe I was experiencing this too. For me, the issue occurred when respawning in dimensions without `height` and `min_y` set (servers from before those fields existed). I worked around this in my mod by creating a temporary thing that added these fields and meant to report it but never got around to it. My error was `Failed to decode: No key height in MapLike`.

**Comment by Earthcomputer** [comment]
Are you using the snapshot version?

**Comment by Kichura** [comment]
> 
> 
> Are you using the snapshot version?

I am indeed using the exact version as described in the snapshot branch including the latest snapshot at time of writing this comment.

**Comment by Earthcomputer** [comment]
Please note that hypixel is not supported on the snapshots.

**Comment by Kichura** [comment]
> 
> 
> Please note that hypixel is not supported on the snapshots.

Not quite as true since your mod still sets the version protocol to 1.16.4/1.16.5 so that snapshot users can connect, but the new dimension connection drop still applies in this section.
