### ISSUE TITLE
Seems incompatible with lithium.

### ISSUE THREAD

**Issue by Pairman** [Earthcomputer/multiconnect#149]
Only tested in 1.15.2 by now. Or should be titled as "lithium incompatible with multiconnect".
The moment after having joined a server(I joined some 1.14.4 servers), the game instantly shows "Saving world" and keeps stuck to this screen. When lithium is removed, the game is just fine.
The crash log just says "unexpected error thrown", and doesn't show anything about lithium or multiconnect.
Weird.

**Comment by Earthcomputer** [comment]
Please use the latest version of multiconnect
