### ISSUE TITLE
[1.16.4] --> [1.12.2] (Disconnect) Non [a-z0-9/._-] character in path of location: minecraft:ITEM.BOTTLE.FILL_DRAGONBREATH

### ISSUE THREAD

**Issue by Felix14-v2** [Earthcomputer/multiconnect#150]
I checked it without other mods, but result is the same.
Video: https://youtu.be/e5Vmw0UlG2o

multiconnect-1.3.34
Fabric 0.11.0 / Fabric 0.11.1
Fabric API-0.29.4
Server: play.teslacraft.org

**Comment by Earthcomputer** [comment]
Could you provide the game log?

**Comment by Felix14-v2** [comment]
Unfortunately, I removed it while cleaning my computer. I will try to reproduce this situation again, and collect more information.

**Comment by Felix14-v2** [comment]
For a while, the server just kicked me out, not allowing me to enter, but at one point I was able to repeat the conditions. Here are the logs.
[latest.log](https://github.com/Earthcomputer/multiconnect/files/5918205/latest.log)
Video: https://youtu.be/q7fdkkvhTS4

**Comment by Earthcomputer** [comment]
Already fixed on the snapshots branch, the fix will be released with 1.17
