### ISSUE TITLE
suggestion: dirtmultiversion integration

### ISSUE THREAD

**Issue by arceuss** [Earthcomputer/multiconnect#151]
https://github.com/DirtPowered/DirtMultiversion 
it pretty much lets you join servers on b1.3 and above from modern versions

**Comment by arceuss** [comment]
if your still even working on multiconnect

**Comment by videogame-hacker** [comment]
> if your still even working on multiconnect

dude there's literally a commit from 22 hours ago what are you on

**Comment by Earthcomputer** [comment]
I don't see why it wouldn't already be compatible.

**Comment by arceuss** [comment]
fair enough
