### ISSUE TITLE
[1.15.2 -> 1.12.2] "Error executing task on Client" when connecting to many servers.

### ISSUE THREAD

**Issue by crosspedestrian** [Earthcomputer/multiconnect#152]
I try to connect some 1.12.2 paper servers but all crash with Error executing task on Client.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_636.method_2911(class_636.java:280)
	at net.minecraft.class_636.method_2927(class_636.java:259)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 18225, 121
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1524 game time, 26178607 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:611)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3558641664 bytes (3393 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		amecs: Amecs 1.2.9+1.15-pre5
		appleskin: AppleSkin 1.0.8
		autoconfig1u: Auto Config v1 Updated 1.2.4
		autoharvest: autoharvest 1.0.4
		clientcommands: Client Commands 2.3.7-pre6
		cloth: Cloth Events 1.2.0
		cloth-basic-math: Cloth Basic Math 0.4.1
		cloth-config2: Cloth Config v2 2.11.1
		durabilityviewer: Giselbaers Durability Viewer 1.15.2-fabric0.4.23-1.7
		easiervillagertrading: EasierVillagerTrading 1.14.4-fabric0.4.1-1.4
		fabric: Fabric API 0.4.32+build.292-1.15
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825de8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+933c24c242
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b395
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.8+build.184
		gbfabrictools: GBfabrictools 1.1.0
		itemscroller: Item Scroller 0.15.0-dev.20200616.032713
		lightoverlay: Light Overlay 4.3
		litematica: Litematica 0.0.0-dev.20200515.184506
		lithium: Lithium 0.3.2
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		me_shedaniel_cloth_basic-math: basic-math 0.3.0
		minecraft: Minecraft 1.15.2
		minihud: MiniHUD 0.19.0-dev.20200508.032934
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.10.2+build.32
		mousewheelie: Mouse Wheelie 1.4.0+1.15.2-pre1
		multiconnect: MultiConnect 1.2.9
		multiconnect-api: MultiConnect API 1.2.9
		optifabric: Optifabric 1.0.0
		orderly: Orderly 2.0.0-alpha+build.7-1.15
		org_jetbrains_annotations: annotations 18.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		phosphor: Phosphor 0.3.6
		replaymod: Replay Mod 1.15.2-2.4.1
		roughlyenoughitems: Roughly Enough Items 3.6.4
		tellme: TellMe 0.8.0-beta.1
		tweakeroo: Tweakeroo 0.10.0-dev.20200715.165541
		tweed: Tweed API 2.2.8
		voxelmap: VoxelMap 1.9.26
		waila: Hwyla 1.9.22
		worldedit: WorldEdit 7.1.0;8e55131
		worldeditcui: WorldEditCUI 1.15.2_03
	Launched Version: HMCL 3.3.172
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2070 Super/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.20, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Depixel1.15.zip, file/Masa_模组汉化资源包_V1.3-全版本.zip
	Current Language: 简体中文 (中国)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre10
	OptiFine Build: 20200327-015852
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.20
	OpenGlRenderer: GeForce RTX 2070 Super/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
#@!@# Game crashed! Crash report saved to: #@!@# D:\模组整合包\.minecraft\versions\1.15.2_Fabric&OptiFine\crash-reports\crash-2021-02-11_11.00.17-client.txt
Saving all world maps
AL lib: (EE) alc_cleanup: 1 device not closed`

**Comment by Earthcomputer** [comment]
Update to the latest version
