### ISSUE TITLE
armor stand is invisible

### ISSUE THREAD

**Issue by MODKILLER1001** [Earthcomputer/multiconnect#153]

**Comment by Earthcomputer** [comment]
Please give more information. What version of multiconnect are you using? What version are you connecting to?

**Comment by MODKILLER1001** [comment]
I am using 1.3.34 and connecting to a 1.16.4 server

**Comment by MODKILLER1001** [comment]
on a 1.16.4 client

**Comment by Earthcomputer** [comment]
Which server are you on?
