### ISSUE TITLE
Biome borders sometimes appear as plains

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/multiconnect#154]
... particularly where you log in. Tested connecting from 21w08a to 1.14.0
![2021-02-28_12 38 17](https://user-images.githubusercontent.com/13084089/109418761-e2768800-79c1-11eb-956d-2d97de3e2c20.png)

**Comment by Earthcomputer** [comment]
Caused by http://github.com/Earthcomputer/multiconnect/blob/e5616c0e29fbfab7a593ecf7a257c5381e982316/src/main/java/net/earthcomputer/multiconnect/protocols/v1_16_5/Protocol_1_16_5.java#L129 ?

**Comment by haykam821** [comment]
This is a vanilla bug.
