### ISSUE TITLE
Trouble with certain carpet options.

### ISSUE THREAD

**Issue by the-just-luke** [Earthcomputer/multiconnect#159]
This may work for other versions but at least when using a 1.16.5 client, when logging onto a 1.16.3 server the carpet rule creativeNoClip doesn't work anytime you relog without putting in the command /carpet creativeNoClip true even if it already enabled/defaulted to true on the server.

**Comment by Earthcomputer** [comment]
This is due to multiconnect blocking custom payloads from older server versions. Multiconnect has an API to listen for and send these custom payloads explicitly to older servers. Tweakeroo or whatever clientside mod you are using for noclip must use this API to work on older servers.
