### ISSUE TITLE
Different Position

### ISSUE THREAD

**Issue by MCSuchter** [Earthcomputer/multiconnect#16]
It would be very good if its possible to have a different Button position because some Mods have buttons at the top left at the Multiplayer Screen
![Button](https://user-images.githubusercontent.com/49833081/72203472-537c7880-346c-11ea-9279-56a9872e36b8.PNG)

**Comment by Earthcomputer** [comment]
I'm planning on removing the button from this screen anyway, and making it individual for each server

**Comment by Earthcomputer** [comment]
Try the new prerelease
