### ISSUE TITLE
Multiconnect API Deprecated ModMenu Features

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Earthcomputer/multiconnect#160]
This is put in logs when using something that uses Multiconnect API:

`[main/WARN]: WARNING! Mod multiconnect-api is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.`

`[main/WARN]: WARNING! Mod multiconnect-api is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

**Comment by Earthcomputer** [comment]
Fixed by #164
