### ISSUE TITLE
Error when connecting to 1.8 server

### ISSUE THREAD

**Issue by RaphiMC** [Earthcomputer/multiconnect#166]
This error gets thrown when connecting to a 1.8 server: https://pastebin.com/3y7Z0UUM

Steps to reproduce:
* Connect to a 1.8 server
* Open the inventory

Notice: This error only occurs once, after that the error doesn't get thrown anymore (Restart multiconnect to get error again)

MultiConnect: 1.8 branch latest version as of writing this issue
Testserver: Spigot 1.8.8 with no plugins installed

**Comment by Earthcomputer** [comment]
Fixed in snapshots branch, will be merged into 1.8 branch soon.
