### ISSUE TITLE
Mount desync

### ISSUE THREAD

**Issue by UltraBlackLinux** [Earthcomputer/multiconnect#167]
Hey there,
I just tried to mount a horse, and I always got that one weird mount desync, where you are not actually mounted - Even with multiconnect it didn't work, even though I thought this would fix it - is there a solution for this?
Am I doing something wrong?
https://streamable.com/0pxm8l
Thanks!

**Comment by Earthcomputer** [comment]
If it doesn't work without multiconnect then it's broken somewhere else, and you can't expect multiconnect to fix issues like that.

**Comment by UltraBlackLinux** [comment]
@Earthcomputer well it's a bug that seems to occur frequently with 1.13+, even on servers that officially support those versions too - I hoped multiconnect would fix this, as 1.12 and such are perfectly working on that server.

**Comment by Earthcomputer** [comment]
Again, it's a problem with the server, not a problem with multiconnect
