### ISSUE TITLE
[1.14 -> 1.13.2] Crawling should be disabled

### ISSUE THREAD

**Issue by RaphiMC** [Earthcomputer/multiconnect#171]
Multiconnect: 1.3.36
Server: Spigot 1.12.2

Crawling should be disabled in versions where it didn't exist, else it allows an unfair advantage: https://streamable.com/5lk3db

**Comment by Earthcomputer** [comment]
Isn't crawling a 1.13 thing too?

**Comment by RaphiMC** [comment]
I also thougt so, but I checked it and it doesn't seem like it works in 1.13
