### ISSUE TITLE
[1.9] Block placement bugs

### ISSUE THREAD

**Issue by RaphiMC** [Earthcomputer/multiconnect#172]
Multiconnect: 1.3.36
Server: Spigot 1.9

The player shouldn't be able to place blocks inside of him and other players: https://streamable.com/hvmw0g

**Comment by creeper123123321** [comment]
related to https://github.com/ViaVersion/ViaFabric/issues/25

**Comment by Earthcomputer** [comment]
Just to clarify, this only happens on Spigot.

**Comment by Earthcomputer** [comment]
I just fetched the latest Spigot there is for 1.9.4 and couldn't reproduce this.

**Comment by RaphiMC** [comment]
This happens on spigot 1.9.0 or paper 1.8.8

**Comment by RaphiMC** [comment]
1.13 -> 1.12.2 changed the condition when a block place is sent / when the client doesn't send one. For example it doesn't when you try to place inside an other entity and in 1.13 it does.

**Comment by Earthcomputer** [comment]
Now I'm on Spigot 1.9.0 and it's still not happening
