### ISSUE TITLE
[Bug] Slime blocks disappeared from litematics

### ISSUE THREAD

**Issue by Metacinnabar** [Earthcomputer/multiconnect#175]
### Description
Using multiconnect 1.16.4 connecting to a 1.12.2 server and loading in a litematic using masa's litematica mod, all the slime blocks were replaced with air blocks in the litematic, even though slime blocks existed in 1.12 and 1.16.

### Info
Multiconnect Version: multiconnect-1.3.36
Litematica Version: litematica-fabric-1.16.4-0.0.0-dev.20201103.184101
If cannot reproduce, I'll send the litematic

**Comment by Earthcomputer** [comment]
Just a heads up, bug reports are invalid unless you're on the latest version of multiconnect. But I doubt this has been fixed with the update.
