### ISSUE TITLE
Crashed while connecting to 1.16.5 from 1.17

### ISSUE THREAD

**Issue by GoodPro712** [Earthcomputer/multiconnect#176]
### Description
Game crashed while connecting to a 1.16.5 server from 1.17 multiconnect. Seems to be a mixin error.

### Files
Crashlog: 
[crash-2021-06-09_16.36.15-client.txt](https://github.com/Earthcomputer/multiconnect/files/6621580/crash-2021-06-09_16.36.15-client.txt)

**Comment by Earthcomputer** [comment]
Does this happen with just multiconnect installed? If not, can you find out which mod it conflicts with?

**Comment by Earthcomputer** [comment]
It seems to be an incompatibility with ItemScroller. I'll look into it

**Comment by GoodPro712** [comment]
Ahh I was just testing them and didn't notice your reply. Thanks for the fast reply

**Comment by Earthcomputer** [comment]
Try multiconnect 1.4.2

**Comment by GoodPro712** [comment]
Thanks!
