### ISSUE TITLE
CIT not working when connecting to server

### ISSUE THREAD

**Issue by dbrighthd** [Earthcomputer/multiconnect#179]
I tried to connect to my 1.16.5 server with a 1.17 client, and optifine custom item textures are not working (renamed items).

**Comment by dbrighthd** [comment]
not sure if this has already been dealt with or said it won't be fixed, but I couldn't find it in any previous issues.

No worries if its not fixable!

**Comment by Earthcomputer** [comment]
optifine is not compatible with multiconnect, please use mods from this list of optifine alternatives: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754 and https://irisshaders.github.io/ for shaders. If you really want optifine compatibility, please report it to the OptiFabric repo.
