### ISSUE TITLE
[Crash] multiconnect incompatible with Not Enough Crashes

### ISSUE THREAD

**Issue by Mhowser** [Earthcomputer/multiconnect#18]
Mod link: https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes

Stacktrace: https://0bin.net/paste/j1dACcx8QaHBzGFK#xXjkmcPN7CrZmBwlu4wXXlo8oifNYV0qrtjFaHChIoG

Launcher log: https://0bin.net/paste/tCLJ9FfIdySlfmeB#ezFbEh7PWpGCCH02Vf7odmOCDR9LL+CDc+GOjU3d4QY

**Comment by Earthcomputer** [comment]
Looks like Fudge fixed it on his end: https://github.com/natanfudge/Not-Enough-Crashes/issues/9
