### ISSUE TITLE
[1.17] → [1.12.2] Dropping chunk/light update packet

### ISSUE THREAD

**Issue by Felix14-v2** [Earthcomputer/multiconnect#182]
Some terrain and light data doesn't loaded at all with log warn "Dropping chunk/light update packet at ..., ... because it was too far away from the render distance center ..., ..."

[Demo](https://youtu.be/xnpZ4pe6j4I) (with ban :D)
[latest.log](https://github.com/Earthcomputer/multiconnect/files/6646492/latest.log)

There are also some other minor bugs in logs.

Problematic server: Play.TeslaCraft.org

**Comment by lenrik1589** [comment]
Earth, to reproduce, use 1.17 client and log onto proto (might only affect qwp, but still) no terrain is loaded and you just float helplessly in midair

**Comment by Felix14-v2** [comment]
The problem is still there. But now I have "Unexpectedly disconnected from server!" message in logs (Packet 0/50 (class_2716) was larger than I expected, found 5 bytes extra whilst reading packet).
https://youtu.be/36JdX9sriGI
[latest.log](https://github.com/Earthcomputer/multiconnect/files/6772378/latest.log)

**Comment by Earthcomputer** [comment]
You're using multiconnect for 1.17.1 on 1.17.0, please update to 1.17.1

**Comment by Felix14-v2** [comment]
1.17.1 shows absolutely the same result :(

Even crazier:
[latest.log](https://github.com/Earthcomputer/multiconnect/files/6772544/latest.log)

**Comment by Earthcomputer** [comment]
Please try with just multiconnect installed. Some of your other mods in that list might be interfering

**Comment by Felix14-v2** [comment]
Absolutely the same. Only multiconnect and fabric API installed.

**Comment by lenrik1589** [comment]
seems to work fine for me with 1.4.5, @Felix14-v2

**Comment by Earthcomputer** [comment]
I fixed the bug I was told to reproduce, it might be that there are multiple bugs with the same symptoms

**Comment by Earthcomputer** [comment]
@Felix14-v2 your specific issue seems to caused by the server sending weird teleport packets. I'll try to look into it further
