### ISSUE TITLE
inputs via custom mod are dropped

### ISSUE THREAD

**Issue by ayunami2000** [Earthcomputer/multiconnect#184]
client: 1.17
server: ANY (including 1.17 AND SINGLEPLAYER!!)
logs: Dropping untranslated serverbound click slot packet, sent without the client player interaction manager

if you could either fix this or help me to fix my mod to become compatible then i will see it as fixed either way

edit: would like to clarify that no issues occur when multiconnect is removed (except of course I cannot join 1.16.5 and below servers)

**Comment by Earthcomputer** [comment]
You need to send the click slot packet via `MinecraftClient.getInstance().interactionManager.clickSlot`, rather than sending the packet directly

**Comment by ayunami2000** [comment]
How would I get the variables for this, like syncId

**Comment by Earthcomputer** [comment]
Oh, you're sending a creative mode click. Then you need `MinecraftClient.getInstance().interactionManager.clickCreativeStack`

**Comment by ayunami2000** [comment]
Thank you, that fixed it!
