### ISSUE TITLE
[1.16.5]->[1.14.4] Player tossing when climbing floating scaffolding blocks

### ISSUE THREAD

**Issue by Pairman** [Earthcomputer/multiconnect#188]
Screenshots: https://photos.app.goo.gl/sSSz3fbsDwesic5H6
Player position tossing up and down when climbing between two blocks to a floating scaffolding block. Therefore the player cannot go further up in this state.

My computer has problem with 1.17 fabric so I cannot test this on 1.17.

**Comment by Earthcomputer** [comment]
> My computer has problem with 1.17 fabric so I cannot test this on 1.17.

You need to install Java 16

**Comment by Earthcomputer** [comment]
Happens with vanilla 1.14.4 clients.
