### ISSUE TITLE
Multiconnect allows 1.17 clients to leash squids

### ISSUE THREAD

**Issue by CalXee** [Earthcomputer/multiconnect#194]
You can leash squids in older versions in 1.17. Doing so doesn't actually consumes the lead, or move the squid. It just removes a lead and draws a ghost lead that doesn't do anything and can stretch infinite length. The lead is only removed client side and thus updating the stack visually gets the lead back.

**Comment by Earthcomputer** [comment]
https://github.com/Earthcomputer/multiconnect/commit/0d3b4a063f8d4f98bc1c48f90587627967c5c5e5
