### ISSUE TITLE
Merge with https://github.com/Earthcomputer/Connect-to-1-12-x

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/multiconnect#2]
Same thing for different versions. Merge into one Repo?

**Comment by MCRcortex** [comment]
that will happen eventually (hopefully) but first have to go through 1.13

**Comment by Earthcomputer** [comment]
No it's not the same thing, they are 2 different mods for 2 different modloaders, one is forwards compat and one is backwards compat.
