### ISSUE TITLE
og-sg.net 1.8 cannot join

### ISSUE THREAD

**Issue by MCRcortex** [Earthcomputer/multiconnect#200]
When joining og-sg.net with multiconnect 1.8 I reliably get this disconnect error log:
https://pastebin.com/kRtE3r3D

**Comment by UltraBlackLinux** [comment]
I have a somewhat similar problem: https://paste.ee/p/C3iLo

**Comment by Earthcomputer** [comment]
@UltraBlackLinux that is not a multiconnect issue, multiconnect disables itself on hypixel. That would be hypixel's translator messing up.
