### ISSUE TITLE
version dropdown not there

### ISSUE THREAD

**Issue by xhendrikg** [Earthcomputer/multiconnect#206]
The Version dropdown doesnt show when you connected to a server after i connected to a server as 1.8 on a 1.17.1 server and client 
![grafik](https://user-images.githubusercontent.com/69456711/126546480-26f54d16-fa92-41d0-9858-73d47bb30aac.png)

I just restarded my client and its still not there. huh

**Comment by Earthcomputer** [comment]
There's not supposed to be a version dropdown on that screen, it's in the "edit server" screen.
