### ISSUE TITLE
Possible mod incompatibility: Lithium

### ISSUE THREAD

**Issue by Mhowser** [Earthcomputer/multiconnect#21]
https://github.com/jellysquid3/Lithium

I'm trying to connect to `2b2tpvp.net` (1.12.2), but if I have Lithium loaded, Minecraft absolutely craps the bed attempting to connect, throwing the same error until I force close the game.

https://paste.dimdev.org/olicudirib.mccrash

**Comment by Earthcomputer** [comment]
Yes, if you want to use Lithium with this mod, you're on your own. Lithium messes with too much random stuff, and given that it's a server mod (hence only useful in singleplayer) I don't really want to officially support it. Try turning off different Lithium settings until it works.

**Comment by CDAGaming** [comment]
@Mhowser If your still wishing to do this, use the following config:

[lithium.txt](https://github.com/Earthcomputer/multiconnect/files/4182264/lithium.txt)
Ensure you rename the file to lithium.toml and replace the existing lithium config with this

**Comment by eatmyvenom** [comment]
For future reference, it is now `lithium.properties` and not toml

**Comment by Earthcomputer** [comment]
Reopening as I've decided on being compatible with lithium.

**Comment by Earthcomputer** [comment]
Lithium settings known to be incompatible with multiconnect so far:
- `mixin.entity.data_tracker.use_arrays`

**Comment by Earthcomputer** [comment]
Try version 1.3.6

**Comment by Mhowser** [comment]
Will do, thanks!
