### ISSUE TITLE
cannot join 1.12.2-

### ISSUE THREAD

**Issue by RafWasTaken** [Earthcomputer/multiconnect#210]
i cannot join on any other version older  then 1.13, for example if i try to 1.13 it lets me but on 1.12.2 1.11 1.10 1.9 1.8 it dosent let me

**Comment by Earthcomputer** [comment]
Please say what your multiconnect version is, and upload your game log

**Comment by RafWasTaken** [comment]
i have 1.4.8 and it says timed out/discconected, or cannot load raw ids

**Comment by Earthcomputer** [comment]
I said post the game log

**Comment by RafWasTaken** [comment]
there is a couple

**Comment by Earthcomputer** [comment]
Please just upload one where the bug happened on. I can't even begin to understand it without that

**Comment by RafWasTaken** [comment]
![error](https://user-images.githubusercontent.com/84086804/127503075-5a10a2f0-03c3-4781-a14a-820a1a758be6.png)

**Comment by Earthcomputer** [comment]
Bruh I said a log not a screenshot

**Comment by RafWasTaken** [comment]
but it dosent crash tho

**Comment by Earthcomputer** [comment]
game log not crash log

**Comment by RafWasTaken** [comment]
wdym

**Comment by xpple** [comment]
Go to your Minecraft folder and then to the directory `logs`. Paste or upload the `latest.log` file here.

**Comment by Earthcomputer** [comment]
Thanks

**Comment by Earthcomputer** [comment]
I can't reproduce the problem, it might be a mod compat issue. Could you try removing some mods to find out which one(s) it might be conflicting with?

**Comment by RafWasTaken** [comment]
i removed both and nothing still cant join

**Comment by Earthcomputer** [comment]
Both of what? Does it work with multiconnect on its own?

**Comment by RafWasTaken** [comment]
both of the mods, i had multiconnect,fabric,meteor client,and iris shaders a i removed meteor and iris and still cant join server that are 1.12.2 or older

**Comment by Earthcomputer** [comment]
You have baritone, fabric API, iris, meteor, multiconnect and sodium. When I say "multiconnect on its own" I mean try removing baritone, fabric API, iris, meteor and sodium, and see if you can then connect.

**Comment by Earthcomputer** [comment]
Actually you can try it with fabric API, since I also tried it with fabric API and couldn't reproduce

**Comment by RafWasTaken** [comment]
btw yes i do have barione but the baritone is from meteor

**Comment by Earthcomputer** [comment]
Does it work on a different server?

**Comment by RafWasTaken** [comment]
wdym

**Comment by Earthcomputer** [comment]
If you try a different server than 9b9t does it then work?

**Comment by RafWasTaken** [comment]
nope

**Comment by Earthcomputer** [comment]
Working fine for me:
![Screenshot from 2021-07-29 16-35-37](https://user-images.githubusercontent.com/13084089/127521716-0a833b85-658c-41f8-a468-6cb6cf02ac2c.png)

**Comment by RafWasTaken** [comment]
not for me tho

**Comment by xpple** [comment]
Have you now tried to remove all other mods from the `mods` folder?

**Comment by RafWasTaken** [comment]
yep i tried, nothing changed

**Comment by RafWasTaken** [comment]
by nothing changed i mean still cannot join

**Comment by Earthcomputer** [comment]
Closing as cannot reproduce
