### ISSUE TITLE
[1.17.1] -> [1.12.2] Hovering over death item in chat does not show enchantments.

### ISSUE THREAD

**Issue by mpeg41** [Earthcomputer/multiconnect#212]
I am trying to hover over a message that shows the item a player was killed by. Doing this will only display the item without the actual item's name and enchantments. I can confirm that using 1.12.2 shows the correct enchantments and name for the item.

My log does not produce any errors or warnings.

**Comment by Earthcomputer** [comment]
Duplicate of #44
