### ISSUE TITLE
Client crashing by redstone projects when using Multiconnect 1.16.5 > 1.12.2

### ISSUE THREAD

**Issue by PortalZii** [Earthcomputer/multiconnect#213]
Playing on 2b2t which uses version 1.12.2. I have been using multi-connect on the server for a few days using Minecraft launcher 1.16.5 and 1.16.5 fabric mods without issue and connecting to 1.12.2 server using multi connect.

While everything was stable for days the client started crashing the moment i activated redstone pistons.

Here is my crash log: https://paste.ee/p/TWQRI

Thanks for any help

**Comment by Earthcomputer** [comment]
1.16.5 is not supported, update to 1.17.1. This issue is not related to multiconnect anyway

**Comment by PortalZii** [comment]
You are right the issue wasnt related to multi-connect. Also i do not wish to update im on this version for a reason.

Either way i removed some optimization fabric mod i forgot i had which solved my issues. Thanks for your time. Love your project!
