### ISSUE TITLE
Random crash issue when lithium is installed and joining servers with multiconnect on 1.14 protocol or less

### ISSUE THREAD

**Issue by Justsnoopy30** [Earthcomputer/multiconnect#214]
[crash-2021-08-05_16.53.42-client.txt](https://github.com/Earthcomputer/multiconnect/files/6941898/crash-2021-08-05_16.53.42-client.txt)

**Comment by Earthcomputer** [comment]
I don't think this is in fact related to lithium, but rather one of the other mods you have installed. I've added a check for this case which gracefully handles this case and also prints more useful debug information.
