### ISSUE TITLE
Unable to join 1.17 Server

### ISSUE THREAD

**Issue by IThundxr** [Earthcomputer/multiconnect#216]
![image](https://user-images.githubusercontent.com/74031881/128584694-0cbf976e-3105-43ac-aeca-c600944acc2c.png)
![image](https://user-images.githubusercontent.com/74031881/128584741-95916f55-da95-4f6b-8af1-de566444d577.png)
attached are the client side mods and the error

**Comment by Earthcomputer** [comment]
The server has a content mod
