### ISSUE TITLE
World corruption on Cuberite servers when using 1.9-1.12.2 protocol.

### ISSUE THREAD

**Issue by OrangeCatSeth** [Earthcomputer/multiconnect#218]
https://cuberite.org/demoservers/
1.12.2 is currently the newest version supported by Cuberite.

Multiconnect 1.9-1.12.2:
![2021-08-07_16 31 27](https://user-images.githubusercontent.com/24788083/128614405-632d4672-b108-4a14-9819-6b80310a29a7.png)

Multiconnect 1.8:
![2021-08-07_16 36 45](https://user-images.githubusercontent.com/24788083/128614452-e8fbc1d5-5fe8-429d-a659-d602b3f315fb.png)

Vanilla 1.12.2:
![2021-08-07_16 39 45](https://user-images.githubusercontent.com/24788083/128614524-7441676b-bdbb-4466-ba7f-cdc667df7ac6.png)

**Comment by Earthcomputer** [comment]
It's weird that the air is staying intact

**Comment by Earthcomputer** [comment]
This issue is unlikely to persist after the rewrite. Please reply if it does.
