### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by trolle6** [Earthcomputer/multiconnect#219]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/6949966/latest.log)

joined a 1.16.5 server on a 1.17.1 client got kicked this is what i got

**Comment by Earthcomputer** [comment]
Duplicate of #178. Do you guys not get the rare bug report screen that links you to that bug? Anyway, thanks for uploading your game log

**Comment by JackTGG** [comment]
Hello trolle
