### ISSUE TITLE
Error connecting to 2b2t (1.12.2) from 1.17.1

### ISSUE THREAD

**Issue by redpenguinyt** [Earthcomputer/multiconnect#229]
2b2t is a spigot 1.12.2 anarchy server (or a branch of spigot)
I'm trying to join 2b2t from 1.17.1 and am unable to join

I get errors like `java.runtimeException` and something to do with black and orange beds :/

My mods:
litematica (I tried without it and got the same errors)
lithium
sodium
meteor client (hacks for 2b2t)
modmenu
multiconnect 1.4.12

**Comment by Earthcomputer** [comment]
Duplicate of #163
