### ISSUE TITLE
Can't connect to 1.16 server from 1.17

### ISSUE THREAD

**Issue by edwloef** [Earthcomputer/multiconnect#231]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/7055998/latest.log)

**Comment by tantokwa** [comment]
Try disabling colormatic. We have a somewhat similar modlist and when I disabled colormatic I was able to join 1.16.5 servers.

**Comment by edwloef** [comment]
Thanks. Maybe colormatic should be marked incompatible then?

**Comment by Earthcomputer** [comment]
No, that sounds like a poor fix compared to actually fixing the issue
