### ISSUE TITLE
[1.12.2] Using BlockItems on blocks in adventure mode does not send an item use to the server

### ISSUE THREAD

**Issue by Felix14-v2** [Earthcomputer/multiconnect#241]
When pointing any item at a block, the client does not send data about the use of the item to the server.
It is also impossible to click on the signs.

How it should be: [[Demo]](https://youtu.be/cGP0IBsW0FA)
What we have: [[Demo]](https://youtu.be/Q8GNxaBi198)

**Comment by Earthcomputer** [comment]
I can't reproduce the issue with the signs:
![Screenshot from 2021-09-07 14-22-10](https://user-images.githubusercontent.com/13084089/132352054-7f3cade2-f4ce-4278-848c-819fb064ee30.png)

**Comment by Earthcomputer** [comment]
This appears to happen in adventure mode

**Comment by Felix14-v2** [comment]
Can't confirm in new versions, I think it's fixed now
