### ISSUE TITLE
Some subchunks are missing connecting to a 1.14.4 server.

### ISSUE THREAD

**Issue by LiamMCW** [Earthcomputer/multiconnect#256]
While trying to debug a different issue, I set up a 1.14.4 vanilla server and a new client instance with only multiconnect. When I joined the server and started flying around I noticed missing pieces of the world. They act like ghost blocks and right clicking on where the block should be or having the block change on the server side causes the block to reappear. Mobs inside the missing terrain are where they should be.

![2021-10-02_16 18 46](https://user-images.githubusercontent.com/35670972/135730763-7f608abf-39dc-4b05-895d-6e56f17123fe.png) 

![2021-10-02_16 24 04](https://user-images.githubusercontent.com/35670972/135730875-f4490b4a-598a-475b-9d5a-f045605c565c.png)

**Comment by LiamMCW** [comment]
Not sure if I should create a new issue for this but certain block updates also don't show up, for example if I place a torch then break the block under the torch, I see the item drop but the torch becomes a ghost block and stays floating until I right-click or any other anti-ghost block method.

**Comment by Felix14-v2** [comment]
This is very similar to #209, but torch updates looks like new issue.

**Comment by Earthcomputer** [comment]
What version are you using? I recognize the torch issue and light issue from some time ago, but it was fixed

**Comment by LiamMCW** [comment]
I'm using a version I compiled from the master branch today. The version number is 1.4.15.
