### ISSUE TITLE
Errors will be catched and the catch produces an direct buffer exception

### ISSUE THREAD

**Issue by Sumandora** [Earthcomputer/multiconnect#271]
https://github.com/Earthcomputer/multiconnect/blob/d70f7e4ec8cd3ba4f0cbb45265c02dd686d2a182/src/main/java/net/earthcomputer/multiconnect/impl/DebugUtils.java#L290
This catch is a problem.
If a exception is being catched and is recognized as an "unexpected disconnect" then in.array() will be called.
This can lead to a direct buffer and the original error will go unknown.
Printing the error before calling in.array() might be a temporary fix.

**Comment by Earthcomputer** [comment]
This is already fixed in the snapshots branch
