### ISSUE TITLE
New 1.18 version crashes on startup

### ISSUE THREAD

**Issue by cd1213** [Earthcomputer/multiconnect#272]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_6734 failed
Exit Code: -1

[crash-2021-11-30_22.19.44-client.txt](https://github.com/Earthcomputer/multiconnect/files/7628931/crash-2021-11-30_22.19.44-client.txt)

No mods except the newest versions of fabric-api and multiconnect.

**Comment by Earthcomputer** [comment]
Thanks for reporting, I'll get round to it shortly

**Comment by Earthcomputer** [comment]
Try version 1.5.1

**Comment by cd1213** [comment]
1.5.1 works, thanks
