### ISSUE TITLE
Crash when in a certain area on 1.16.5 server using Multiconnect 1.5.2 on minecraft 1.18

### ISSUE THREAD

**Issue by Venaf** [Earthcomputer/multiconnect#287]
[Crash report](https://pastebin.com/JeY3wzdQ)
[Log](https://pastebin.com/4BRCfABt)
Looks like it's happening when loading a particular chunk in/near my base.

**Comment by Sneakometer** [comment]
https://pastebin.com/YeWnF9cu

**Comment by Earthcomputer** [comment]
Hi, please don't upload logs to expiring pastebins, can you reupload it please?

**Comment by Earthcomputer** [comment]
This looks like a mod incompatibility. Can you try with different combinations of mods and let me know which mod(s) multiconnect is incompatible with?

**Comment by Venaf** [comment]
Very sorry about the original log issue and late reply, I hadn't played since and wasn't checking github.  Looks like I've narrowed it down to Iris causing the crash:

[Crash Report](https://pastebin.com/BVx9UH4y)
[Log](https://pastebin.com/1vHdt0Ak)

Whether with the rest of my mods or without, adding Iris causes it to happen.

**Comment by Venaf** [comment]
I'm also seeing some chunks not visually load with Sodium, without Iris.
