### ISSUE TITLE
Error joining gommehd.net Server using Version 1.18.1 with selected Version 1.8

### ISSUE THREAD

**Issue by AstragoDE** [Earthcomputer/multiconnect#289]
### Server IP:
gommehd.net

### Multiconnect Version:
1.5.4

### Minecraft Version:
1.18.1

### Selected Minecraft Version (Server Protocol Version):
1.8

### Fabric Version:
0.12.11

## Error:
[Screenshot 1/1](http://cdn.astrago.de/images/screenshots/Screenshot%202021-12-11%20153334.png)

**Comment by Sumandora** [comment]
Restart a few times and try again. The registry stuff really has to be recoded.

**Comment by AstragoDE** [comment]
After a few restarts, everything works as intended.
Thank you for your support.
