### ISSUE TITLE
[1.9 -> 1.8] Block place sounds are played twice

### ISSUE THREAD

**Issue by RaphiMC** [Earthcomputer/multiconnect#298]
A 1.8 client doesn't play the block place sound clientside and its only played by the server.
1.9 plays it clientside and not serverside, so playing with a 1.9+ client on 1.8 results in two block place sounds to be played

**Comment by OrangeCatSeth** [comment]
Duplicate of #187

**Comment by RaphiMC** [comment]
Oh didn't see that
