### ISSUE TITLE
Mixin apply for mod multiconnect failed (Critical injection failure)

### ISSUE THREAD

**Issue by R4z0rX** [Earthcomputer/multiconnect#309]
Hi!

`@Inject annotation on onCreatePacket could not find any targets matching 'sendPacket(Lnet/minecraft/server/network/ServerPlayerEntity;Lnet/fabricmc/fabric/impl/registry/sync/packet/RegistryPacketHandler;)V' in net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.`

Minecraft 1.18.1
Fabric Loader 0.12.12
Fabric API 0.45.1
Multiconnect 1.5.8
[latest.log](https://github.com/Earthcomputer/multiconnect/files/7802643/latest.log)

**Comment by xpple** [comment]
Please update to the latest version of multiconnect.

**Comment by R4z0rX** [comment]
Wow, you're fast! xD It's working again. Thank you @Earthcomputer! 👍🏻
