### ISSUE TITLE
Crash getting server chunk biome with Sodium 0.4.0 

### ISSUE THREAD

**Issue by qeou** [Earthcomputer/multiconnect#317]
It appears that loading certain chunk biomes with Sodium 0.4.0 results in a crash. This does not occur without multiconnect

Client version: 1.18.1
Server version: 1.17.1

Mods:
- notenoughcrashes-4.1.3+1.18.1-fabric.jar
- sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar
- fabric-api-0.46.0+1.18.jar
- multiconnect-1.5.10.jar

Associated log:
- Crashy - [https://crashy.net/Gs646WSznLRzOP3NUyLS](https://crashy.net/Gs646WSznLRzOP3NUyLS)
- Raw - [https://bytebin.lucko.me/5DIUv6jub4](https://bytebin.lucko.me/5DIUv6jub4)

**Comment by Earthcomputer** [comment]
This is unlikely to occur after the rewrite. Please reply if it does.
