### ISSUE TITLE
Kicked after joining server with carpet-autoCraftingTable and Fabric API

### ISSUE THREAD

**Issue by Floris0106** [Earthcomputer/multiconnect#32]
I've first had this problem quite a while ago and i couldn't figure out what the problem was, but today i narrowed it down to multiconnect. Same issue on carpet-autoCraftingTable: https://github.com/gnembon/carpet-autoCraftingTable/issues/2

**Comment by Earthcomputer** [comment]
Multiconnect cannot be installed alongside other mods unless they are client-side-only.
