### ISSUE TITLE
Incompatibility with mod

### ISSUE THREAD

**Issue by energy11a** [Earthcomputer/multiconnect#327]
With multiconnect installed shulker-dupe mod does not work, without multiconnect it works fine.
https://github.com/Coderx-Gamer/shulker-dupe

**Comment by Username404-59** [comment]
This issue is probably caused by shulker-dupe not supporting multiconnect, not the other way around, and developers don't usually support cheats.

**Comment by JaaiDead** [comment]
> This issue is probably caused by shulker-dupe not supporting multiconnect, not the other way around, and developers don't usually support the use of cheats.

Yes We dont :) @energy11a

**Comment by JaaiDead** [comment]
Close Issue
