### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by jLn0n** [Earthcomputer/multiconnect#331]
currently multiconnect mod doesn't support 1.18.2, it would be great if 1.18.2 support is added

**Comment by VytskaLT** [comment]
he's working on it

**Comment by jLn0n** [comment]
oh ok

**Comment by Earthcomputer** [comment]
I'm going to place a $50 bounty on this. Check my discord for how the bounty system works, and discuss with me about what is left to be done for this update.

**Comment by JaaiDead** [comment]
Im gonna work on this :DDDD

**Comment by SachiIang** [comment]
Can't wait for you to finish.

**Comment by VytskaLT** [comment]
> Can't wait for you to finish.

Then try finishing it yourself.

**Comment by SachiIang** [comment]
well that will take a while, I don't know what to change

**Comment by JaaiDead** [comment]
@SachiIang  It will take a while a lot longer.

**Comment by Earthcomputer** [comment]
> don't know how to get to the discord

There is an invite link in the readme

**Comment by DarkblooM-SR** [comment]
Do we have an idea of when it will release?

**Comment by JaaiDead** [comment]
@DarkblooM-SR  Currently No idea . If you wanna help join the discord. its in readme 
im working on it .

**Comment by DarkblooM-SR** [comment]
@JaaiDead I don't know any Java lol not sure how I can help

**Comment by Earthcomputer** [comment]
Due to the apparent difficulty of this task, I'm going to be doubling the bounty up to $100.

**Comment by JaaiDead** [comment]
WOW

**Comment by mrplayergod** [comment]
Why isnt multi connect getting 1.18.2 it has been so long

**Comment by JaaiDead** [comment]
PRs Are Welcomed :) .

**Comment by CormacZ** [comment]
Oh my, 1.18.2 does really break this mod that it took a while to update it

**Comment by JaaiDead** [comment]
@CormacZ  Yes , it breaks most of it .

**Comment by FireTner** [comment]
a while to update it? I don't see any update yet? or am I wrong?

**Comment by mrplayergod** [comment]
How much people is working on this if it's 20 why is it so long

**Comment by fxmorin** [comment]
@mrplayergod It's 1 xD Earth, and its long cause Mojang changed something which was critical for multiconnect

**Comment by mrplayergod** [comment]
Okay am sorry now i understand why it's so long @fxmorin

**Comment by haze** [comment]
I heard @jordin had a working version in a private fork

**Comment by Earthcomputer** [comment]
The bounty for this has ended - it's been superseded and overtaken by the translation rewrite

**Comment by JaaiDead** [comment]
Close Issue 📦
