### ISSUE TITLE
Multiconnect conflicts with optifabric

### ISSUE THREAD

**Issue by SachiIang** [Earthcomputer/multiconnect#334]
Any time i want to play minecraft on a different version and want to do it with multiconnect, i have to add multiconnecta and remove optifine and optifabric
![image](https://user-images.githubusercontent.com/69481715/160259439-04f0315b-004c-4ba0-9722-c1360f7d54c0.png)

**Comment by Username404-59** [comment]
Multiconnect explicitly is incompatible with optifine, this is wanted

**Comment by Gaming32** [comment]
Here is a more full list of [OptiFine Alternatives](https://lambdaurora.dev/optifine_alternatives/).
