### ISSUE TITLE
help???

### ISSUE THREAD

**Issue by Hermmm** [Earthcomputer/multiconnect#338]
[15:11:09] [ForkJoinPool-1-worker-1/WARN]: The mod "multiconnect" contains invalid entries in its mod json:
- Unsupported root entry "__comment__" at line 42 column 16

**Comment by Earthcomputer** [comment]
1.17.1 is outdated

**Comment by Earthcomputer** [comment]
If you need further support please join the discord in the readme instead of creating issues
