### ISSUE TITLE
IndexOutOfBoundsException when trying to connect to realms world

### ISSUE THREAD

**Issue by Mhowser** [Earthcomputer/multiconnect#34]
https://paste.dimdev.org/moxesutopu

Both the client and the realm are 1.15.2

**Comment by Earthcomputer** [comment]
Can you send the whole log?

**Comment by Mhowser** [comment]
I will on lunchtime.

**Comment by Mhowser** [comment]
here you go https://paste.dimdev.org/odirimimuk

**Comment by Earthcomputer** [comment]
Please test with multiconnect on its own and let me know if the same error happens.

**Comment by Mhowser** [comment]
Ok so I did that and I was able to connect, I also tested which mods might be causing the problem and I have narrowed it down to Immersive Portals mod. Here is the jar for testing (remove .zip extension)
[immersive-portals-0.12formc1.15withfabric.jar.zip](https://github.com/Earthcomputer/multiconnect/files/4216684/immersive-portals-0.12formc1.15withfabric.jar.zip)

**Comment by Earthcomputer** [comment]
Does it happen even without realms?

**Comment by CDAGaming** [comment]
Verified it may be with Immersive Portals. With earlier tracking, Immersive Portals is modifying the PlayerPositionLookS2CPacket, and throwing in Multiconnect from it (Best guess from looking at this)

**Comment by Mhowser** [comment]
if i connect to a normal server? I get this error when tring to connect to us.mineplex.com https://paste.dimdev.org/wudajejeqe.nginx

**Comment by Earthcomputer** [comment]
https://github.com/qouteall/ImmersivePortalsMod#breaking-hacks
Multiconnect is not compatible with both-sided mods in general, let alone those with "breaking hacks". Please use a separate profiles for multiconnect and immersive portals.

**Comment by Mhowser** [comment]
Understandable, I will ditch Immersive portals since I dont really need it anyway, thanks for help!
