### ISSUE TITLE
Register multiconnect particles for 1.17 and check they work

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/multiconnect#348]
- `multiconnect:barrier`
- `multiconnect:light`

These two particles replace `minecraft:barrier` and `minecraft:light` that were removed in 1.18

**Comment by Gaming32** [comment]
Wait, so what does it do to render barriers and light blocks now? Does it do the same thing as Bedrock now, where it's an actual block model?

**Comment by JaaiDead** [comment]
yes i think we can report to performance mods i think
