### ISSUE TITLE
When placed comparator on chunk with repeating command block it will turn into button

### ISSUE THREAD

**Issue by ZeoNight** [Earthcomputer/multiconnect#349]
When placed comparator on chunk with repeating command block it will turn into button

**Comment by Gaming32** [comment]
I have one question for you: how on earth did you find this bug?

**Comment by Earthcomputer** [comment]
I tried to place a comparator next to a repeating command block. Then tested it with and without a repeating command block in a different chunk

**Comment by Gaming32** [comment]
But why did you think to test it in the first place?

**Comment by Earthcomputer** [comment]
Found by accident while trying to test something else

**Comment by Gaming32** [comment]
Classic 😎
