### ISSUE TITLE
Multiconnect does not ignore/block unrecognized custom payloads

### ISSUE THREAD

**Issue by Mhowser** [Earthcomputer/multiconnect#35]
![image](https://user-images.githubusercontent.com/24195572/76677661-4411cc80-658e-11ea-8136-66415d5221b2.png)
When I try to connect to a 1.12.2 server I get disconnected immediately while these errors appear in the game log.

The server is `MC.BUILDERSREFUGE.COM`

**Comment by CDAGaming** [comment]
This was previously seen before but only when FabricAPI was loaded in a setup

**Comment by Earthcomputer** [comment]
I am still not entirely sure on the best way to fix this. I think probably non-vanilla custom payloads should be blocked by multiconnect by default, and then add a way in the API for mods to transform custom packets.

**Comment by lenrik1589** [comment]
also crashes connection to the 1.12.1 when opening statistics menu (PT)
![Screenshot from 2020-04-16 21-22-53](https://user-images.githubusercontent.com/48890625/79558721-498e9500-80ad-11ea-9700-a49b5b946c2c.png)

**Comment by Earthcomputer** [comment]
@lenrik1589 the statistics menu issue should be fixed in the latest multiconnect. The `minecraft:register` thing is still an issue, however.

**Comment by Earthcomputer** [comment]
In the fix for this, I will block non-vanilla custom payload packets coming from older versions from triggering normal handing of custom payload packets. I will add an API to instead allow custom handle these packets.

**Comment by Earthcomputer** [comment]
To fix this, I had to change a little how the API loads. The new API is still binary compatible with mods already using the old one (so no need for a major version bump), but the way it loads could cause issues if the player has an older version of multiconnect than the version of the API another mod is using. So therefore, the new API will be part of the 1.16 version of multiconnect, where players will have to install the new multiconnect anyway.
