### ISSUE TITLE
1.16.5 doesnt allow elytra trigger

### ISSUE THREAD

**Issue by ZeoNight** [Earthcomputer/multiconnect#350]
1.16.5 doesnt allow elytra trigger

No stacktrace. Serverside needs more debugging

**Comment by PHPCore1** [comment]
On 1.16.5 when you give yourself an elytra in creative, it will be a snowball on the server (try use it with right click when in hand).

**Comment by JaaiDead** [comment]
Let me test it

**Comment by JaaiDead** [comment]
Issued Fixed Close.
