### ISSUE TITLE
Storage error when connecting to servers

### ISSUE THREAD

**Issue by nijahplays** [Earthcomputer/multiconnect#357]
Got the error
![Screenshot from 2022-06-07 20-59-18](https://user-images.githubusercontent.com/70035007/172515094-b7dd4906-7306-4e00-9829-21b762998c1d.png)

**Comment by nijahplays** [comment]
1.19 servers specifically

**Comment by nijahplays** [comment]
And I wasn't given an error log

**Comment by Earthcomputer** [comment]
@nijahplays can you upload your game log? It should be in `.minecraft/logs/latest.log`

**Comment by nijahplays** [comment]
> @nijahplays can you upload your game log? It should be in `.minecraft/logs/latest.log`

There were no logs created for the error

**Comment by nijahplays** [comment]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/8864091/latest.log)


Got it

**Comment by Earthcomputer** [comment]
I don't see multiconnect in your mods list. Also, can you check the new release to see if it works with that?

**Comment by nijahplays** [comment]
Fixed by updating to beta
