### ISSUE TITLE
io.netty.handler.codec.DecoderException: Unknown serializer type -1

### ISSUE THREAD

**Issue by nijahplays** [Earthcomputer/multiconnect#359]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/8867038/latest.log)

**Comment by FernandoPelarich** [comment]
I have the same error: im connecting from 1.19 to a 1.18.2 server, and when it teleports me to another world in the same server, it kicks me saying that error.

**Comment by TheDeafCreeper** [comment]
Getting the same issue (1.19 -> 1.18.1) when loading a specific area (not sure what the area is)

**Comment by nijahplays** [comment]
Please remember to provide error logs!

**Comment by TheDeafCreeper** [comment]
Good point, here's my [latest.log](https://github.com/Earthcomputer/multiconnect/files/8885279/latest.log)

**Comment by Earthcomputer** [comment]
I have added some extra info to the logs in beta.13 to help me debug this issue. Since there is a higher memory overhead, you have to opt-in to this extra logging.
Please add `-Dmulticonnect.storeBufsForHandler=true` to your JVM arguments and then give me the log file when this happens again

**Comment by TheDeafCreeper** [comment]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/8887188/latest.log)
Here you go, the flag should be enabled

**Comment by Earthcomputer** [comment]
Could you try again with https://github.com/Earthcomputer/multiconnect/suites/6904779592/artifacts/268086601? Sorry, my debug message was dumping the wrong packet

**Comment by TheDeafCreeper** [comment]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/8892267/latest.log)

**Comment by nijahplays** [comment]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/8894242/latest.log)

Here's mine as well
