### ISSUE TITLE
Shulker boxes disappear from inventory

### ISSUE THREAD

**Issue by Pairman** [Earthcomputer/multiconnect#36]
This mod is great! But when I use the mod for 1.15.2 to join 1.15.2 and 1.14.4 servers, some of my shulker boxes especially the dyed ones in my inventory are lost. Please fix this bug, thanks!

**Comment by Earthcomputer** [comment]
I can't reproduce this, maybe it's related to the items inside your shulker boxes? Could you share which items are inside an affected shulker box?

**Comment by CDAGaming** [comment]
It also might help to mention which version of multiconnect this issue occured on in this case

**Comment by Earthcomputer** [comment]
Can't reproduce and got no response, closing. Please let me know if this is still an issue.
