### ISSUE TITLE
[1.19]→[1.12.2] io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by Felix14-v2** [Earthcomputer/multiconnect#360]
**Description**
Unable to join to 1.12.2 server (play.teslacraft.org) – disconnect with an error `io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(38) + length(4) exceeds writerIndex(38): PooledUnsafeDirectByteBuf(ridx: 38, widx: 38, cap: 38)`
[[Demo]](https://youtu.be/azWWe4gr62U)
Occurs even without any other mods.

**Technical**
Minecraft version: 1.19
multiconnect version: 1.6-beta.12
Server version: 340 (1.12.2)

**Additional**
[latest.log](https://github.com/Earthcomputer/multiconnect/files/8874482/latest.log)

There are also many packet errors in logs.

**Comment by BookWyrm114** [comment]
I've also been getting errors like these, but for 1.19 -> 1.18.2

![image](https://user-images.githubusercontent.com/79489385/173166030-db4a658f-ef77-4a6a-aba6-8a7a6e070f8c.png)

**Comment by Earthcomputer** [comment]
@BookWyrm114 that is not the same error. Yours looks like #359
