### ISSUE TITLE
[1.19] Four issues

### ISSUE THREAD

**Issue by DarkReaper231** [Earthcomputer/multiconnect#363]
1. I tested this on 1.18.2 spigot while connecting to that server using multiconnect 1.19 but when I click on villagers, I get this error
![2022-06-12-022520_1920x1080_scrot](https://user-images.githubusercontent.com/38611351/173253964-5cb71070-8011-48e1-88fa-2948e946b62f.png)

2. I am playing minigames server. They have viaversion and the backend server runs 1.8
    There is a problem
    I am connecting to that server with multiconnect on 1.19
    I am playing build battle and the block placing and block breaking is kinda broken
    It works but there are visual glitches
    Like the block kinda appears, then quickly vanishes and appears again
    Best I could describe it is block blinking
    When placing down redstone, it's even worse and the redstone dust is doing some weird visual stuff

3. When I type /plugins on 1.18.2 server I get this error
![2022-06-12-234857_1920x1080_scrot](https://user-images.githubusercontent.com/38611351/173255065-dbdf3958-c43e-46d4-be5b-7719c6030ecd.png)

4. When connecting some 1.17 servers I get this error
![2022-06-13-002400_1920x1080_scrot](https://user-images.githubusercontent.com/38611351/173256072-fe1dc04f-4507-4a64-b240-5ddb91d363ee.png)

Also could you maybe add upload actions so I can download latest fixes from Actions?

**Comment by Earthcomputer** [comment]
> Also could you maybe add upload actions so I can download latest fixes from Actions?

PRs welcome.

**Comment by Earthcomputer** [comment]
I would rather you created separate issues rather than one mega issue, it makes it easier to track them.

**Comment by DarkReaper231** [comment]
> I would rather you created separate issues rather than one mega issue, it makes it easier to track them. And please upload logs. They help me reproduce the issue.

Okay I'll do it tomorrow

**Comment by DarkReaper231** [comment]
Fuck it I'll do it now

**Comment by DarkReaper231** [comment]
> I would rather you created separate issues rather than one mega issue, it makes it easier to track them. And please upload logs. They help me reproduce the issue.

Done

**Comment by DarkReaper231** [comment]
> > Also could you maybe add upload actions so I can download latest fixes from Actions?
> 
> PRs welcome.

Also done

**Comment by Earthcomputer** [comment]
I think this issue has been superseded by others
