### ISSUE TITLE
Disconnects on Hypixel

### ISSUE THREAD

**Issue by nijahplays** [Earthcomputer/multiconnect#368]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/8887990/latest.log)

:/

Kicked from game consistently

**Comment by Earthcomputer** [comment]
Can you describe what you were doing when the error occurred?

**Comment by nijahplays** [comment]
It's happened at seemingly random intervals, each being completely different scenarios.

**Comment by nijahplays** [comment]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/8915413/latest.log)


Here's another instance of this happening

**Comment by nijahplays** [comment]
Fixed by installing indium

Odd interaction with continuity mod
