### ISSUE TITLE
[1.19] -> [1.12.2] Unknown type minecraft:flower_pot

### ISSUE THREAD

**Issue by OrangeCatSeth** [Earthcomputer/multiconnect#374]
Attempting to connect to bridger.land using 1.12.2 protocol or lower fails on multiconnect 1.6-beta 14.
![2022-06-14_14 40 45](https://user-images.githubusercontent.com/24788083/173675208-5c957aca-8db8-49b9-9e19-5ed32411f952.png)
[latest (copy).log](https://github.com/Earthcomputer/multiconnect/files/8903510/latest.copy.log)

**Comment by Earthcomputer** [comment]
@Felix14-v2 that looks like a conflict with bobby, but I guess I can fix it. Could you create a new issue for it with the full log?

**Comment by Felix14-v2** [comment]
> looks like a conflict with bobby

I thought the same, however, it was not confirmed in an isolated instance with just multiconnect and bobby. Still looking for the 3rd participant.

**Comment by Earthcomputer** [comment]
Packet recording is automatically enabled when you join a server, if you have `-Dmulticonnect.enablePacketRecorder=true` in your JVM args.

**Comment by RealIndrit** [comment]
Alternatively, You can also turn on the packet recorder by going through the mod menu Multiconnect config screen
