### ISSUE TITLE
1.19 -> 1.18.2 issue with world height

### ISSUE THREAD

**Issue by wagyourtail** [Earthcomputer/multiconnect#384]
reproduce: go on nucleoid.xyz and try to join taterspleef

this is the main one, but it also seems some "silently" failed earlier without kicking me
`Compressed packet data: H4sIAAAAAAAA/+2ZsUrDUBSGT2KhqC1tnIVCwBewDg4u2qgUawPV6NjN2U3HuPkKunT3FazgLE7uhj6Br1CTe3JBJeaWBHuL9/+W75Dh/DeHQG5yXUpZIapR/dwf9LzhSTA42O3sx1c3qks3z5PL7XU428noEteoceyfdv3+cK/nd466/UNMb/bp0ZO7HFYq9La6OWqFNilwBMXNVZ715jsKXEFxc5XnfOQUilo9A+Qvcn5bUNxc5Xmx7x/5evPx/P3vfMu2yJqmVHljMGq97IS27pWpwJsZ+Xj+zJ2/6fl//WYmYDTfdgbGX/kyFystGrKwSVb1Stj8SInemeiVicaPgmj8IIjG93cJsW8TYl9fxSS+iEl8FgSBsOd5wlvtNtt12WtOapJGPvKRj3zkIx/588+fZQfAu4Vydhy2RT89n/zfDQAAAJhI2NS9AgBAHvLXXhnLPllGvsn5U2A0YVP3CgAAAAAwfyz8BFDDo9L3EcDHJOUs+2RZBR/PlLPsk2UVfCxUzrJPllXwcVQ5yz5ZBgAAPXwC4Xsx1fA7AAA=`

https://mclo.gs/ZBR0lSN

second log with `-Dmulticonnect.storeBufsForHandler=true`: https://mclo.gs/z2gzZ3k

**Comment by Earthcomputer** [comment]
This seems to be caused by an issue with the world height mismatching between the client and the server

**Comment by wagyourtail** [comment]
@Earthcomputer is the worldheight/dimension info sent in an earlier packet, and because you're only replaying the one packet it just has an issue in your test env?

**Comment by wagyourtail** [comment]
yeah, I just ran with beta.15 to confirm it's still happening
yep
`H4sIAAAAAAAA/21Q0U6EMBA08QP8hdpniJwiAd79CmMuS9mDnqV7KQVsLvyUX+iiFyUefduZ6ezs3H3enqUiQ06WMqAxNMlI4od3IMvXP6pxEJjwzPAk5+iK0rZH5zVZhiZoAg3OgzbMKKPV+8uIlr+eJaiLqB+aBnu/V9R1YGsWjmAGZObBcxCxMhG8ULY0otuwaWnaM6j9kkKR9Tz0i8SH0+LWaYvKwcGXJwMB3ZK1ZjwvkiLNiiyudukhTtMsi6F6TOJklz/XyVNRFzmw1kKH324/p69Pm+c52sSv29kq7rfuCyla6MWROG4tfIui4c3CUFWFezm/rTxu/r8vwapJ7cYBAAA=`

**Comment by Earthcomputer** [comment]
It's gzip compressed. Is the world height different than vanilla on this server?

**Comment by wagyourtail** [comment]
yeah, ok we're back to the *right* error now, yeah 

```
Compressed packet data: H4sIAAAAAAAA/+2ZsUrDUBSGT2KhqC1tnIVCwBewDg4u2qgUawPV6NjN2U3HuPkKunT3FazgLE7uhj6Br1CTe3JBJeaWBHuL9/+W75Dh/DeHQG5yXUpZIapR/dwf9LzhSTA42O3sx1c3qks3z5PL7XU428noEteoceyfdv3+cK/nd466/UNMb/bp0ZO7HFYq9La6OWqFNilwBMXNVZ715jsKXEFxc5XnfOQUilo9A+Qvcn5bUNxc5Xmx7x/5evPx/P3vfMu2yJqmVHljMGq97IS27pWpwJsZ+Xj+zJ2/6fl//WYmYDTfdgbGX/kyFystGrKwSVb1Stj8SInemeiVicaPgmj8IIjG93cJsW8TYl9fxSS+iEl8FgSBsOd5wlvtNtt12WtOapJGPvKRj3zkIx/588+fZQfAu4Vydhy2RT89n/zfDQAAAJhI2NS9AgBAHvLXXhnLPllGvsn5U2A0YVP3CgAAAAAwfyz8BFDDo9L3EcDHJOUs+2RZBR/PlLPsk2UVfCxUzrJPllXwcVQ5yz5ZBgAAPXwC4Xsx1fA7AAA=
```

```
Caused by: java.lang.IndexOutOfBoundsException: varint too big
	at net.earthcomputer.multiconnect.impl.PacketIntrinsics.readVarInt(PacketIntrinsics.java:248) ~[multiconnect-1.6-beta.16.jar:?]
	at net.earthcomputer.multiconnect.generated.Protocol_1_18_2.translateSPacketChunkData_Latest(Protocol_1_18_2.java:6600)
	```
