### ISSUE TITLE
1.19 Multiconnect breaks fabrication's version checking

### ISSUE THREAD

**Issue by JumperCzech** [Earthcomputer/multiconnect#385]
![image](https://user-images.githubusercontent.com/83337894/174792399-e465af4f-fa2a-425e-8aa9-5ea87a9ba712.png)

client log
https://mclo.gs/cj8djXV
server log
https://mclo.gs/JRr65lz

Fabrication: https://github.com/unascribed/Fabrication/issues/491

**Comment by Earthcomputer** [comment]
This is caused by multiconnect blocking custom payloads. If Fabrication wants to work around this, it needs to use multiconnect's API.
