### ISSUE TITLE
Getting disconnected from server when warden is nearby

### ISSUE THREAD

**Issue by JumperCzech** [Earthcomputer/multiconnect#387]
![Screenshot_3](https://user-images.githubusercontent.com/83337894/175338812-0a207f20-f8b2-4e0a-a4e7-0ef89c596e40.png)

client log: https://mclo.gs/z3gpwyq
server log: https://mclo.gs/vVYvFjL

Can't figure out what exactly is the cause, but the disconnect seems to happen when the warden is nearby and aggroed.

**Comment by Earthcomputer** [comment]
Can you test with `-Dmulticonnect.storeBufsForHandler=true` in your JVM args and send the logs?

**Comment by JumperCzech** [comment]
> Can you test with `-Dmulticonnect.storeBufsForHandler=true` in your JVM args and send the logs?

https://mclo.gs/uB7ZqbP

**Comment by ShadowWalker13** [comment]
Was happening to me as well - was getting disconnected immediately after breaking a block with a warden nearby
