### ISSUE TITLE
[1.19] -> [1.18.2] Biome types not translated (correctly)

### ISSUE THREAD

**Issue by Packsolite** [Earthcomputer/multiconnect#390]
Biome types are not correctly translated in the newest [1.6-beta.16](https://github.com/Earthcomputer/multiconnect/commit/837b2821d4bcf6cd6fbd4926a650ed69bd788a74)

1.19 protocol (correct biome):
![image](https://user-images.githubusercontent.com/102829507/175566516-d7abf040-6d20-4fcb-9238-7eb18e617457.png)

forced 1.18 protocol (wrong biome):
![image](https://user-images.githubusercontent.com/102829507/175566743-8960b8bb-c1f8-47e4-bc24-717eab4e2d38.png)

Tested on server `gommehd.net` (lobby).

**Comment by FernanIGF** [comment]
The same thing happens to me, but from 1.19 to 1.16.5. The mangrove_swamp biome apears randomly
![image](https://user-images.githubusercontent.com/71931361/177571689-c8c15bd7-2187-4152-952a-908bc1847526.png)

**Comment by Earthcomputer** [comment]
Does this still occur in the latest version of multiconnect?

**Comment by Oyssis** [comment]
I remember seeing a forest biome and it just all looked like mangrove swamp also tested on the actual server seems like it was fixed with the 1.19.1 release of multiconnect

**Comment by Oyssis** [comment]
an easy way to test it is to go to a warped forest
beta 20
![2022-08-04_07 58 19](https://user-images.githubusercontent.com/108272967/182767772-e194db7e-9d53-4a13-a6cf-07013661454d.png)
beta 21
![2022-08-04_08 08 32](https://user-images.githubusercontent.com/108272967/182767815-65da5e04-76cc-44d7-b63e-289062e1045d.png)

**Comment by Earthcomputer** [comment]
I asked because one of my recent fixes was likely to fix this as a side effect. I'm going to close this as resolved then, if it comes up again just reply and I'll reopen it.
