### ISSUE TITLE
java.lang.IllegalStateException: Cannot set colorMap twice

### ISSUE THREAD

**Issue by Mhowser** [Earthcomputer/multiconnect#4]
![image](https://user-images.githubusercontent.com/24195572/71289567-4adbcb00-2322-11ea-9703-0fb974fd44d6.png)
This happens when connecting to `minecraft.readjust.se`

**Comment by Earthcomputer** [comment]
I don't get that issue without fabric-api installed. Testing with fabric-api now.

**Comment by Earthcomputer** [comment]
Yep, it's an incompatibility with fabric-api

**Comment by Earthcomputer** [comment]
Fixed in version 1.1.1

**Comment by Mhowser** [comment]
Thanks!
