### ISSUE TITLE
Conflict with OptiFine Language Strings

### ISSUE THREAD

**Issue by jkmartindale** [Earthcomputer/multiconnect#40]
For some reason, using multiconnect causes the OptiFine-modded Video Settings menu to display the names of its strings instead of its actual string content.

![image](https://user-images.githubusercontent.com/11380394/79394540-f5f93b80-7f34-11ea-92fa-6de7fe79c26a.png)

Even stranger is that if you open Video Settings from the title screen right after opening Minecraft, it's fine:

![image](https://user-images.githubusercontent.com/11380394/79395068-137ad500-7f36-11ea-8dca-25efaaad1211.png)

But after loading a singleplayer or multiplayer world, the Video Settings menu in-game or in the title screen are messed up until Minecraft is restarted.

Versions:
Fabric Loader 0.7.9+build.190-1.15.2
Minecraft 1.15.2
multiconnect 1.2.2
OptiFabric 1.0.0-beta8
OptiFine 1.15.2_HD_U_G1_pre13

**Comment by Earthcomputer** [comment]
Ugh, this is optifine breaking multiconnect, not multiconnect breaking optifine. Anyway, I'll see what I can do.

**Comment by Earthcomputer** [comment]
Ah yes, it was optifine doing stupid things again. I found a workaround though!
