### ISSUE TITLE
Nether fog looks darker

### ISSUE THREAD

**Issue by Oyssis** [Earthcomputer/multiconnect#401]
I Was on a soul sand valley and I noticed the fog look darker with the mod

**Comment by JaaiDead** [comment]
https://www.reddit.com/r/Minecraft/comments/mv8t74/is_it_just_me_or_is_the_nether_fog_darker/

**Comment by ZeoNight** [comment]
Not a multiconnect releated bug - It doesn't happen to me.

**Comment by Oyssis** [comment]
Can this be reopened I was right look at the fog here
![2022-07-07_16 03 24](https://user-images.githubusercontent.com/108272967/177780286-7aa658e4-a26f-416a-9e7a-24f3a8995a8e.png)

**Comment by Oyssis** [comment]
oh it says in f3 biome:deep_dark in warped forest

**Comment by Oyssis** [comment]
yeah
