### ISSUE TITLE
[1.19] Exception upon attempting to join a multiplayer server

### ISSUE THREAD

**Issue by Shudfly** [Earthcomputer/multiconnect#402]
Upon attempting to join a multiplayer server, I receive the following error:

`Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $`

Here is an image:

![Screenshot 2022-06-29 161751](https://user-images.githubusercontent.com/35050346/176561501-dc43f2cc-dfed-48c3-a349-641bdc697285.png)

And here is the log from my client:

https://mclo.gs/d6DsuoN

From what I can figure out, the mod is unable to parse the JSON file that is downloaded upon attempting to join a server.
I suppose it's just an issue with the downloaded JSON.

**Apologies in advance if this issue has already been opened, I was unable to find another user with this issue.**

**Comment by Earthcomputer** [comment]
Can you try again to see if it still occurs? I suspect something was up with Mojang's servers
