### ISSUE TITLE
1.19 > 1.18.2 or 1.8.9 doesn't let me join. Due to Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by Seth-the-cat** [Earthcomputer/multiconnect#408]
When I try to join a server thats older I get `Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $`.
Im using fabric 1.19 and the newest fabric api 0.57+1.19.

**Comment by 0DamI0** [comment]
update to beta 17 or later

**Comment by Earthcomputer** [comment]
And show your log next time
