### ISSUE TITLE
1.17 >>> 1.16.5 cant connect to 1.16.x servers (Bug)

### ISSUE THREAD

**Issue by test4514** [Earthcomputer/multiconnect#409]
cant connect to 1.16.x servers
mods used : InGameAccountSwitcher-Fabric , fabric-api-0.36.0 , multiconnect-1.4.4

                                                 failed to connect to the server
 com.google.gson.JsonSyntaxExeption: java.lang.illegalStateException: Expected Begin_object but was string at line 1 colum 1 path $

**Comment by 0DamI0** [comment]
use the latest version for 1.16.5 that you find on github

**Comment by test4514** [comment]
> use the latest version for 1.17 that you find on github

i did

**Comment by Earthcomputer** [comment]
No you didn't, 1.4.17 is the latest version for 1.17.1
