### ISSUE TITLE
Change the color of the flag

### ISSUE THREAD

**Issue by chaojifaming** [Earthcomputer/multiconnect#41]
Hello!
When I add the plugin in version 1.15.2, it will change the color of my flag.
This is a photo without the plugin:
![2020-04-26_10 32 30](https://user-images.githubusercontent.com/64340891/80295902-601da600-87a9-11ea-92d0-3ee5bf202a37.png)

This is the photo after adding the plugin:
![2020-04-26_10 35 07](https://user-images.githubusercontent.com/64340891/80295928-ad017c80-87a9-11ea-8c42-b941e3ed1788.png)

Version: Fabric Loader 0.7.9+build.189-1.15.2

**Comment by Earthcomputer** [comment]
I'm aware of this issue, but it's nice to have a bug report on it now I guess

**Comment by Earthcomputer** [comment]
Hey there, can you please state which version of multiconnect you are using? I can't reproduce this bug.

**Comment by chaojifaming** [comment]
The version I use is 1.2.2
Client version: Fabric Loader 0.7.9+build.189-1.15.2

**Comment by Earthcomputer** [comment]
I reproduced it - it happens on the pattern but not the banner base

**Comment by Earthcomputer** [comment]
Try multiconnect 1.2.4

**Comment by InfoTeddy** [comment]
Can confirm that this issue is fixed in 1.2.4.
