### ISSUE TITLE
Can't connect to some servers

### ISSUE THREAD

**Issue by Oyssis** [Earthcomputer/multiconnect#416]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/9093796/latest.log)

**Comment by Oyssis** [comment]
some even think im using a VPN even though im not

**Comment by Earthcomputer** [comment]
You need to force protocol

**Comment by Oyssis** [comment]
that did not fix it I tried on different versions and it did not work

**Comment by Oyssis** [comment]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/9094988/latest.log)

**Comment by Earthcomputer** [comment]
Multiconnect will have no effect on whether the server thinks you're on a VPN

**Comment by Oyssis** [comment]
yeah but the vpn thing is a different problem right?

**Comment by Oyssis** [comment]
well turns out its not a multiconnect issue tested without multiconnect but im not getting those same errors in log and I think its fastload causing this issue
