### ISSUE TITLE
1.19 -> 1.18.2 NullPointerException

### ISSUE THREAD

**Issue by smaks6** [Earthcomputer/multiconnect#417]
![image](https://user-images.githubusercontent.com/68917968/179000752-f16d1500-458b-4811-b793-e9e70a2e5432.png)

**Comment by Earthcomputer** [comment]
Please send the log rather than a screenshot

**Comment by Earthcomputer** [comment]
Closing due to lack of information

**Comment by smaks6** [comment]
@Earthcomputer 
I'm sorry that so long. I have not received notification of your message
Logs:
https://pastebin.com/JULJ2xn9
