### ISSUE TITLE
Unable to enter worlds and servers with EssentialClient installed

### ISSUE THREAD

**Issue by CommandLeo** [Earthcomputer/multiconnect#419]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

An error occurs when trying to access either singleplayer worlds or multiplayer servers while the latest version of EssentialClient for 1.19 is installed. I was told by Sensei that the issue is caused by MultiConnect.
Multiconnect version: 1.6-beta.18.
Here is a list of the mods I'm using: https://pastebin.com/mcc6be3p .
I'll be attaching logs of both the situations described above.

### Log File

Single player world: https://pastebin.com/FMU83pYw ; multiplayer server: https://pastebin.com/musUUGpG

**Comment by Earthcomputer** [comment]
try without replaymod

**Comment by CommandLeo** [comment]
Still getting an error.
Single player world logs: https://pastebin.com/EXZbRC7Z
Multiplayer server logs: https://pastebin.com/F3i4XVkq

**Comment by JaaiDead** [comment]
I think the solution is we need to modify the essential packets making them the version you wanna join ?

**Comment by Earthcomputer** [comment]
The multiplayer issue is a bug with plusls-carpet-addition

**Comment by CommandLeo** [comment]
Indeed, removing plusl-carpet-addition (while keeping ReplayMod) did fix the multiplayer issue, but not the singleplayer one.
Should the issue be kept open for the singleplayer error, should it remain closed, or should I create a new one?
