### ISSUE TITLE
Crash upon launch. (1.17.1 Multiconnect 1.4.17)

### ISSUE THREAD

**Issue by shlermingo** [Earthcomputer/multiconnect#420]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

Upon launching Minecraft 1.17.1 with Multiconnect the game crashes. Discovered this with other mods installed but the paste included is of a client only containing Multiconnect and Fabric API. Both clients I have experienced this issue on launch without Multiconnect. I have no pending Java updates.

### Log File

https://pastebin.com/er8w8gdH

**Comment by Earthcomputer** [comment]
Outdated versions of multiconnect are not supported. In this case downgrading Fabric API to 0.45.0 fixes the issue.
