### ISSUE TITLE
[1.19] -> [1.12.2] Block updates are not handled correctly in chunks with negative Z coordinates

### ISSUE THREAD

**Issue by LostLuma** [Earthcomputer/multiconnect#422]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

While trying out the patch for #421 I ran into an issue that block updates in chunks with negative Z coordinates that are not directly caused by the player are not handled properly. I've posted about this on the Discord before in regards to placing beds ([see here](https://discord.com/channels/703363189081112647/703364312915509249/979596036513357874)), but never opened an issue.

Rather than showing the newly updated blocks in the current chunk the updates will be shown in the first chunk in the negative X direction with the same Z coordinate, and only sometimes (in the case of water) also in the correct chunk.

I've recorded a video of me placing water to demonstrate the behavior here as it's the easiest to do, however it also happens with sand that falls due to other sand, beds, decaying leaves, and likely more:

https://user-images.githubusercontent.com/38926001/179853960-c50550ca-e65c-4935-be29-30797686d09f.mp4

I'm pretty sure this also happens when translating newer versions as the first time I ran into this issue when I posted about it on Discord was from version 1.18.2 to 1.15.2, however I do not have any other non-updated servers around to test currently.

### Log File

https://files.lostluma.dev/3jAdvA.txt

**Comment by LostLuma** [comment]
Thanks for the quick response! I don't think this fix is entirely correct, placing and removing water to cause enough updates now makes all other subchunks turn invisible / empty.

**Comment by Earthcomputer** [comment]
That sounds like a different issue...
