### ISSUE TITLE
Invalid payload register

### ISSUE THREAD

**Issue by Oyssis** [Earthcomputer/multiconnect#424]
### Latest Version?

- [x] I confirm I have the latest version of multiconnect

### Description

The new version of multiconnect made it so I cant log into only that server in beta 18 I could connect to that server

### Log File

https://pastebin.com/y9pNhNxY

**Comment by Earthcomputer** [comment]
This was one of the reasons I blocked non-vanilla custom payloads in the first place.
See #81 and https://github.com/FabricMC/fabric/issues/849
I'm not sure what the best solution is. Perhaps a config option for the server, in addition to the protocol version?
