### ISSUE TITLE
Spamming chat with empty messages

### ISSUE THREAD

**Issue by Oyssis** [Earthcomputer/multiconnect#428]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

only managed to reproduce on that server

### Log File

https://pastebin.com/HwYMsCHW

**Comment by Earthcomputer** [comment]
The server is sending lots of null chat packets

**Comment by Oyssis** [comment]
The server isn't for 1.19 so I tried 1.18.2 and it worked fine is that the server fault?

**Comment by Earthcomputer** [comment]
1.19 disconnects on null chat packets, whereas apparently 1.18.2 ignores them. I had assumed that they should be translated as empty chat packets, hence the behaviour here. I will fix this to drop null chat packets.
