### ISSUE TITLE
Invalid payload REGISTER

### ISSUE THREAD

**Issue by BuggyAl** [Earthcomputer/multiconnect#429]
### Latest Version?

- [x] I confirm I have the latest version of multiconnect

### Description

I am going to be completely honest, I am not sure what is happening. I tried joining a server and it kept kicking me for `Invalid payload REGISTER!`, which I assume is something to do with the latest multiconnect prerelease. The server uses Bungee which kept me on the loading screen forever. Sorry if I'm being stupid.

### Log File

https://mclo.gs/0EKXUHP#L245

**Comment by Earthcomputer** [comment]
Duplicate of #424
