### ISSUE TITLE
F3 + F4 isn't opening gamemode switcher

### ISSUE THREAD

**Issue by Oyssis** [Earthcomputer/multiconnect#433]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

I tried switching gamemodes with F3+F4 and it didn't open gamemode switcher

### Log File

https://pastebin.com/Qm3R5TyN

**Comment by Earthcomputer** [comment]
Can you confirm if you are opped?

**Comment by Earthcomputer** [comment]
Ah.

**Comment by Earthcomputer** [comment]
I'm unable to reproduce this, #434 or #435. Can you try with just multiconnect to at least rule out a mod compat issue?

**Comment by Oyssis** [comment]
Yes I can reproduce #434 and #435 but can't reproduce this issue

**Comment by Oyssis** [comment]
forgot to say the server im on is 1.18

**Comment by Earthcomputer** [comment]
I could tell from the logs ;)

**Comment by Earthcomputer** [comment]
Could you try to figure out which mod is conflicting to cause this issue?

**Comment by Oyssis** [comment]
Okay
