### ISSUE TITLE
Setting server version to 1.17.1 then joining that server you get a crash

### ISSUE THREAD

**Issue by Oyssis** [Earthcomputer/multiconnect#436]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

only managed to reproduce on 1 server

### Log File

https://pastebin.com/xFjbTCkb

### Crash Report (if applicable)

https://pastebin.com/xFjbTCkb

**Comment by Earthcomputer** [comment]
Hi, could you send a packet recording? Add `-Dmulticonnect.enablePacketRecorder=true` to your JVM args, then reproduce the bug, then send me the recording file in `.minecraft/config/multiconnect/packet-logs`

**Comment by Oyssis** [comment]
[mcmanhunt.com-2022-07-21-12-05-53.log.gz](https://github.com/Earthcomputer/multiconnect/files/9157964/mcmanhunt.com-2022-07-21-12-05-53.log.gz)
here

**Comment by Earthcomputer** [comment]
Hmm, the biome seems to be ocean for all of that chunk...
![Screenshot from 2022-07-21 10-21-56](https://user-images.githubusercontent.com/13084089/180179052-fba62e52-f91d-48be-a233-f0d37d5e555b.png)

**Comment by Earthcomputer** [comment]
`H4sIAAAAAAAA/+1YTWvUUBS9CVEzpaXx6UoEk5jRGty0GceNQpuZqqOtQ0dHwY1CcKSI4D8w1CxaV/2YVvxYFREtCLp35U6XIl2K6B9w6ULQe9976XQyKtYPhuq7U+a8e8+995y8bsK4X0R81oDHNugB6IX+8erZSvX0xXCsWjpVOX0cmXyeHdh5a9Sd8+Yr3t3xfU2vRjni68nC8oQ3R/nyxL4Fr1Yp36W+2gz2Ub3C5/JssiDqODdiL+Kc2MdyxtT4wILYR30zBdw/L/oGaD9K0lyuvFz3m5jIvsdnV+qe6Bu1m/n5l/VahefG1IS/mK/LOZYrr9QPLnnzfP8s7sc5f0X6mKU9y+ncCO5hM+kc5gOk59GcyO1Z2sOR5zQn6nhHBrbO9ULf+WptrHzxTL12bKQ0umnubvwP3l3t1+4O4l5QoUKFChX/ZXw81G8Z2+DNrp4l3XfDWO+2oe0qVKhQsTnDyeRMopvBDM9SNjv/k8HkHGPtNnYMSRzM2EgFRSNzXSm/UX2nbe+ajVSvUGpDtndovd4aukyg42bv53uRCmaeVz6XI/WZ1HUz+q7oc12ux5w1dDaon9qQVSbv05H3zgpnRJ7qizqT+qmu9MEPUVQMGsUoKBYb+AnoEwRRhAWsRlQMGljAckRHbEM2CIoRHrFNFAKqYCk4dI56ouLlc5hjBYd4F0ZE++mAfSgURHSIGtqNLWxJD6HpP/dfHXnkx/6nnjfXbu65XbrvN68/9e+U7pWm9qzqkNigW2CDASZAbEMMEFqIiWOCBRrgnw6xQ1TZTkAzQzMEQ6O5YStGdEB3qBRaWHKg9xIMUz/thekQYs1K9u58gHODJ4eR3/0O3w5iF7/MkOZQHaVC5HHe0BBx3jiBEibVgeqEMfGJI/W5VXzJQX4EyjTP9WPyh/7xK7HF/HS4bj/I/ejLcFp1b7oi+IR4U9ekXgdvuJznvt0W3/Lvcn3Oh1ZoGS0f3D/w+5vaTrzT9nxiPrZpnutDmN1/IpnjyDp02/lOXz9G01jzAZTj1eClcj/TmefjvFXO7sk/uaqZY7tWB81wa9y3bn+uQbj01BzWclch0b7NJx+eXEG8sPrsl/x3PM8P+aPvO+v7X/RrZjXm/3yw1vPVFh/uePt7vv4Mfsu/c/R9130pVKhQoUKFfwH5j0oavacYOjw83P0fuFSo+BfC+k/1rQx2W7/bPlSo2FTxFdcSzyWFIwAA`

**Comment by Earthcomputer** [comment]
I can't reproduce. The client is handling the chunk specified in the crash logs perfectly:
![Screenshot from 2022-07-21 10-54-01](https://user-images.githubusercontent.com/13084089/180185899-6eb5e4c3-908d-4c54-9d78-ff207c9d789c.png)

**Comment by Oyssis** [comment]
so another mod is causing it?

**Comment by Oyssis** [comment]
I think its sodium

**Comment by Earthcomputer** [comment]
I can reproduce connecting to the actual server... (without sodium)

**Comment by Earthcomputer** [comment]
There is always a different error beforehand though. You didn't include the full log so I didn't pick up on it...

**Comment by Oyssis** [comment]
it wasnt sodium

**Comment by Oyssis** [comment]
I did send the full log

**Comment by Oyssis** [comment]
the crash log

**Comment by Earthcomputer** [comment]
No, you didn't, you sent the crash log only.

**Comment by Oyssis** [comment]
[latest.log](https://github.com/Earthcomputer/multiconnect/files/9158351/latest.log)

**Comment by Earthcomputer** [comment]
See yeah the real error is above it. This is why I ask for full logs, multiconnect includes useful info to prevent me wasting an hour of my time on a red herring crash log.

**Comment by Oyssis** [comment]
Yeah... you should have told me I thought you only need crash log

**Comment by Earthcomputer** [comment]
It a required field in the template form bruh, you need more telling than that?

**Comment by Oyssis** [comment]
yes

**Comment by Earthcomputer** [comment]
Holy shit

**Comment by Oyssis** [comment]
I actually have 1 more bug I wanted to report I forgot about

**Comment by Earthcomputer** [comment]
Hang on. The error message is saying the server version is 1.19 but the protocol version is forced to 1.19.1 hmmm

**Comment by Earthcomputer** [comment]
Mojang forgot they divided biome coordinates by 4 when printing the coordinates in the crash log. Very misleading, I was looking at the wrong chunk.

**Comment by Oyssis** [comment]
the server version isnt 1.19
