### ISSUE TITLE
Received unexpected null component

### ISSUE THREAD

**Issue by Oyssis** [Earthcomputer/multiconnect#442]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

I tried joining a gamemode on a server and it kicks me everytime

### Log File

https://pastebin.com/t3rhEJdq

**Comment by Earthcomputer** [comment]
The server is sending an invalid packet. Null text components are not supported by 1.19 clients, since you're connecting with the 1.19 protocol this is a problem with the server.
