### ISSUE TITLE
"Connection Lost" on connecting to a server while having Quilted Fabric API

### ISSUE THREAD

**Issue by dylanh12210** [Earthcomputer/multiconnect#445]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

As said; I get a "Connection Lost" error with no description when loading into a server while using Quilted Fabric API (4.0.0-beta1+0.58.5-1.19.1).

### Log File

https://mclo.gs/DPFxIIO

**Comment by Earthcomputer** [comment]
https://github.com/QuiltMC/quilted-fabric-api/issues/15
