### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Oyssis** [Earthcomputer/multiconnect#446]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

btw not using the 1.19.1 version but 1.19 latest I don't think there will be a difference 

### Log File

https://pastebin.com/6mQLaFqM

**Comment by Earthcomputer** [comment]
> btw not using the 1.19.1 version but 1.19 latest I don't think there will be a difference

Please don't do this. Try with the latest version and respond with the new log if it's an issue

**Comment by Oyssis** [comment]
The problem is I have no idea how this crash happend but I will try to reproduce this with the latest release
