### ISSUE TITLE
Disconnects form server due to unexpected packet

### ISSUE THREAD

**Issue by Abled-Taha** [Earthcomputer/multiconnect#447]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

I am playing bedwars on a server network with velocity and join the bedwars server which is on 1.18 and uses via version to support its players, whenever I die, I get disconnected.

### Log File

https://paste.ee/p/8fQ5j

**Comment by Earthcomputer** [comment]
The server is sending an invalid packet
