### ISSUE TITLE
Multiconnect kicks with chat preview

### ISSUE THREAD

**Issue by MODKILLER1001** [Earthcomputer/multiconnect#450]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

If you connect to a server that has chat preview on and use any type of preview option, while typing or before send.
You are kicked from a server. 
![image](https://user-images.githubusercontent.com/17520451/182254042-0d7859c2-55cf-4583-a602-4de3059fbe04.png)

### Log File

https://mclo.gs/j9sqkji

**Comment by Earthcomputer** [comment]
Try this out: https://github.com/Earthcomputer/multiconnect/suites/7618682426/artifacts/316303082

**Comment by MODKILLER1001** [comment]
This fix works, thank you.
