### ISSUE TITLE
Villagers don't trade anything

### ISSUE THREAD

**Issue by Oyssis** [Earthcomputer/multiconnect#454]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

![2022-08-02_16 25 58](https://user-images.githubusercontent.com/108272967/182385972-3fae7a86-9d3d-4e41-b782-044d0a42f64c.png)

### Log File

https://pastebin.com/ntmGs2Lp

**Comment by Earthcomputer** [comment]
Could you create a packet recording for this?

**Comment by Oyssis** [comment]
[game3.falixserver.net%3A50539-2022-08-02-17-19-39.log.gz](https://github.com/Earthcomputer/multiconnect/files/9243017/game3.falixserver.net.3A50539-2022-08-02-17-19-39.log.gz)

**Comment by Earthcomputer** [comment]
It looks like that log file is corrupted :/ could you make another one?

**Comment by Oyssis** [comment]
I will make another one is it because I opened it with notepad just to see whats in there?

**Comment by Oyssis** [comment]
[game3.falixserver.net%3A50539-2022-08-02-22-13-42.log.gz](https://github.com/Earthcomputer/multiconnect/files/9245040/game3.falixserver.net.3A50539-2022-08-02-22-13-42.log.gz)

**Comment by Earthcomputer** [comment]
Yes, that's better, thanks.

**Comment by Earthcomputer** [comment]
Try this version: https://github.com/Earthcomputer/multiconnect/suites/7636672912/artifacts/317523809

**Comment by Oyssis** [comment]
Tried it and everything looks good
![2022-08-03_08 19 13](https://user-images.githubusercontent.com/108272967/182530781-b733fbb3-2ef2-4902-97c4-e0197a3a2662.png)
