### ISSUE TITLE
[1.19.1 -> * (Potentially related to protocol hacks like ViaVersion and ViaBackwards??)] Instant kick as soon as you say anything

### ISSUE THREAD

**Issue by Erisfiregamer1** [Earthcomputer/multiconnect#457]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

Saying anything caused you to be disconnected. A reliable area to test this is Minehut.
Setting the version to anything below 1.19 seems to fix this reliably.

### Log File

Doesn't leave behind an error except on server (server error will be posted shortly), so invalid

### Crash Report (if applicable)

Invalid

**Comment by Earthcomputer** [comment]
Invalid issue due to lack of a log file.

**Comment by Erisfiregamer1** [comment]
I was trying to get the log as we spoke, but alright. @Earthcomputer if I post the error from the server here (Client gives no error) then will it be reopened?

**Comment by Erisfiregamer1** [comment]
Annnnnd the server has no error. How fun!
For now I guess maybe it's something up with the version checks? After all, setting the version to 1.18.1 or 1.17 makes it work fine, so...

**Comment by Earthcomputer** [comment]
As I said, I'm not doing anything without logs. Even if you think there's nothing in them there usually is at least something useful I can glean from it. Can you also try a vanilla client and see if that works?

**Comment by Erisfiregamer1** [comment]
Vanilla works fine.
I'll just send the log from this scenario:
`User Erisfiregamer1 joins "minehut.com" and says "h" in the chat. Version detection is set to auto.`
Give me a minute.

**Comment by Erisfiregamer1** [comment]
Annd here's the log.
Minehut says "An internal error has occured in your connection."
https://paste.ee/p/WKUhb

**Comment by Oyssis** [comment]
Pretty sure its a dupe of #448
