### ISSUE TITLE
Incompatibility with Simple Voice Chat

### ISSUE THREAD

**Issue by Androkai** [Earthcomputer/multiconnect#460]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

Recently I noticed an incompatibility between the multiconnect and [Simple Voice Chat](https://modrinth.com/mod/simple-voice-chat) mods preventing a connection for voice between the client and server. I then contacted @henkelmax, the developer of Simple Voice Chat. He looked into the problem and told me that multiconnect seems to block all non-vanilla communication to the server. This prevents the client mod from connecting to the associated server plugin.

It would be great if a solution could be worked out for this.

### Log File

https://gist.github.com/Androkai/79930164c14dde6e4b25f261122595ed

**Comment by Earthcomputer** [comment]
Hi, you need to tell him to read [this document](https://github.com/Earthcomputer/multiconnect/blob/master/docs/custom_payloads.md) on the subject.

**Comment by henkelmax** [comment]
> Hi, you need to tell him to read [this document](https://github.com/Earthcomputer/multiconnect/blob/master/docs/custom_payloads.md) on the subject.

Thanks, I will look into it!

**Comment by henkelmax** [comment]
Alright, it will work in the next release.

**Comment by Androkai** [comment]
A thank you to both of you.
