### ISSUE TITLE
On the Minecraft Server Herobrine.org With a custom enchantment plugin when i put the enchantment "Light Artifact" on my elytra and open it i get instantly kicked from the server

### ISSUE THREAD

**Issue by JerboaWings1** [Earthcomputer/multiconnect#465]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

I Have an Elytra on the Server Herobrine.org (Specifically the Iris Oneblock game mode) And I have maxed it out with all the custom enchants available for the elytra

![2022-08-13_21 06 17](https://user-images.githubusercontent.com/111455808/185210560-1932259c-8427-4b56-8a05-f19e1fc78109.png)

But Specifically the problem was with The "Light Artifact" enchantment when i added it i opened my elytra and i got kicked with this message:

![2022-08-13_21 06 36](https://user-images.githubusercontent.com/111455808/185210577-ee7c1c13-bd95-4e56-983d-39fc466e68d2.png)

I am running a 1.19 client with the latest multimc version!

### Log File

https://paste.atlauncher.com/view/33d97357-13bd-4130-8779-e203e7acf4c6

**Comment by Earthcomputer** [comment]
Hi, could you add `-Dmulticonnect.storeBufsForHandler=true` to your JVM args, reproduce the bug again, and then send me the log from that?

**Comment by JerboaWings1** [comment]
Ill do that in a bit

**Comment by JerboaWings1** [comment]
oh ok except this is the newest version on atlauncher

**Comment by JerboaWings1** [comment]
k ill try that and ill see if the bug is still there

**Comment by JerboaWings1** [comment]
THE BUG ISNT FIXED

**Comment by Earthcomputer** [comment]
OKAY I WILL REOPEN

**Comment by Earthcomputer** [comment]
Alright could you do the thing I asked for above then?

**Comment by JerboaWings1** [comment]
will do

**Comment by Earthcomputer** [comment]
You have put two JVM arguments into one

**Comment by JerboaWings1** [comment]
fixed it

**Comment by JerboaWings1** [comment]
launching now

**Comment by JerboaWings1** [comment]
there u go:  https://paste.atlauncher.com/view/baa1c184-b767-4464-845c-fcea4f1b00ee

**Comment by Earthcomputer** [comment]
Oh, this is #459, it is fixed, there's just no release for it yet.

**Comment by JerboaWings1** [comment]
well when will there be a release, i want to use multiconnect as currently i cant use it due to this bug

**Comment by JerboaWings1** [comment]
its fixed but i wish i could use 1.19 as other mods i use havent been updated
