### ISSUE TITLE
[1.19.2 -> 1.19.0] Non [a-z0-9/._-] chatacter in path of location: minecraft:Summoner

### ISSUE THREAD

**Issue by TheDeafCreeper** [Earthcomputer/multiconnect#467]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

(MultiConnect Version: 1.6-beta.23)

### Description

When attempting to connect to one of the servers on my network I get kicked with the error in the tittle (full error: `Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft.Summoner`)

Server IP if you'd like to verify the issue yourself: play.prolieum.net | Woolsacre Gamemode

It may be due to one of the plugins on the server as the world by itself does not appear to cause the kick.

### Log File

https://drive.proton.me/urls/VY8A81WP94#KRvgvry61AEC

**Comment by Earthcomputer** [comment]
Have you tried connecting with a vanilla 1.19 client? The server is sending an invalid packet.
