### ISSUE TITLE
A 1.18.2 version

### ISSUE THREAD

**Issue by UniqueName12345** [Earthcomputer/multiconnect#472]
### Description

Pretty simple. A mod I'm using only supports 1.18.2, and the only 1.18 version is for 1.18.1.

- [ ] Change the API version to 1.18.2
- [ ] Modify the code for 1.18.2 support
- [ ] Make a new 1.18.2 release on github

**Comment by UniqueName12345** [comment]
whty

**Comment by Earthcomputer** [comment]
> A mod I'm using only supports 1.18.2

And another mod you're using (multiconnect) only supports the latest version. You need to tell the other mod to upgrade rather than telling me to downgrade.

**Comment by UniqueName12345** [comment]
> > A mod I'm using only supports 1.18.2
> 
> And another mod you're using (multiconnect) only supports the latest version. You need to tell the other mod to upgrade rather than telling me to downgrade.

Technically, it supports 1.18.1 as well..
