### ISSUE TITLE
Quilted Fabric API error on multiconnect version 1.6-beta.23 for Minecraft 1.19.2

### ISSUE THREAD

**Issue by YukiAyase** [Earthcomputer/multiconnect#473]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

**Using multiconnect with ViaFabric on Quilt Loader 0.17.5-beta.2 with Quilted Fabric API (Quilt API) version 4.0.0-beta.11 (QFAPI 4.0.0-beta.11 and QSL [Quilt Standard Libraries] 3.0.0-beta.15) shows 2 errors upon trying to join a server twice [1.19.2 client connecting to 1.19 server]**

Using only multiconnect makes the errors occur
Using only ViaFabric works fine (if this is important to note)

Mods I use are listed in the log file

_If this error is on Quilt's side and/or a duplicate, please close this issue_

_This error happens when you attempt to join the server only for the first time_
![image](https://user-images.githubusercontent.com/64414315/189079278-b27062aa-ab4b-4421-b8ca-c9a167ea2631.png)

_This is error appears after attempting for the 2nd time and keeps occuring after more attempts_
![image](https://user-images.githubusercontent.com/64414315/189079752-2d5c1719-f6b8-44ef-b0b4-dfa22f34a46c.png)

**These errors do not happen when using Fabric API on Quilt loader**

### Log File

https://mega.nz/file/JzQAnCiT#ajfXsbKJTywNt5bYVctZORftJqs9aK5upELoqsfmpC4

**Comment by Oyssis** [comment]
https://github.com/QuiltMC/quilted-fabric-api/issues/15
