### ISSUE TITLE
Please make it available for any version

### ISSUE THREAD

**Issue by THON12032522** [Earthcomputer/multiconnect#475]
### Description

Please make the mod available for every version of Minecraft cause I cannot connect to 1.19.2 servers with the mod for 1.19.

**Comment by wagyourtail** [comment]
the purpose of the mod is to connect to older servers from newer minecraft, not the other way

**Comment by THON12032522** [comment]
well it's called multiconnect it would be cool to be able to connect to newer versions from 1.19 to 1.19.2 or from 1.18 to 1.18.2 wouldn't it???

**Comment by THON12032522** [comment]
Oh yeah, I was asking because the mods I use are for 1.19 and not 1.19.2 that's why

**Comment by Felix14-v2** [comment]
> I use are for 1.19 and not 1.19.2

Most of all mods for 1.19 are compatible with further versions. You can always change the target version in the `fabric.mod.json` file, included in the mod's archive.

**Comment by THON12032522** [comment]
I have already tried but the mod keeps crashing

**Comment by Earthcomputer** [comment]
You need to tell those mod authors to upgrade, instead of telling me to downgrade.

**Comment by THON12032522** [comment]
Who are the mod authors

**Comment by Felix14-v2** [comment]
> Who are the mod authors

You can open its repos by links from their descriptions in ModMenu.

**Comment by THON12032522** [comment]
Okay
