### ISSUE TITLE
Crash on server with resource pack

### ISSUE THREAD

**Issue by SemmieboyYT** [Earthcomputer/multiconnect#48]
I was just playing around and when I joined my server on 1.12.2 (my client was on 1.15.2, I turned that option on, so I can join it), everything worked fine. The resource pack installed correctly. But when I got kicked, the game crashed. I have 2 other mods installed, the name and links are:
OptiFabric (https://www.curseforge.com/minecraft/mc-mods/optifabric)
OptiFine (http://optifine.net/adloadx?f=preview_OptiFine_1.15.2_HD_U_G1_pre18.jar)
Here is the crash report: 
[crash-2020-05-31_08.36.37-client.txt](https://github.com/Earthcomputer/multiconnect/files/4707202/crash-2020-05-31_08.36.37-client.txt)

Also, it might not matter, but my server is running git-Spigot-2f5d615-aae46f8 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) and I have ViaVersion with ViaBackwards and ViaRewind.

If you need any more information, you can just ask me.

**Comment by Earthcomputer** [comment]
Is there a server resource pack? Mind sending the whole log?

**Comment by Username404-59** [comment]
The problem does not come from multiconnection because it has nothing to do with the protocol, so it surely comes from optifine/optifabric.

**Comment by Earthcomputer** [comment]
The problem may well relate to multiconnect, the stack trace seems to suggest that the item registry is being modified while being iterated over by optifine (while resources are reloaded) after he got kicked. Multiconnect changes round the item registry when the protocol changes. In fact, it *might* be possible to reproduce without optifine, I am just waiting on more info from him.

**Comment by Earthcomputer** [comment]
This issue has been inactive for 3 days or more, so it is assumed to be resolved and will be closed. If it was not resolved, simply reply again and it will be reopened.
