### ISSUE TITLE
Game doesn't load due to "Redundant texture list for particle multiconnect:depth_suspend"

### ISSUE THREAD

**Issue by DangerMage** [Earthcomputer/multiconnect#481]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

When starting the game it acts as though it is constantly reloading a resource pack and the buttons are squares

checking the log it looks like probably a mod conflict

The log has the entire mods list, java args, java version, etc.

Ignore the broken narrator libraries, that is a bug with multimc at this time.

### Log File

https://paste.ee/p/A4xpX

**Comment by Earthcomputer** [comment]
Can you find out which mod it's conflicting with please?

**Comment by DangerMage** [comment]
> Can you find out which mod it's conflicting with please?

Looks to be custom splash screen

I am using version 1.2.0 of custom splash screen.

**Comment by Earthcomputer** [comment]
I would report this to them, multiconnect doesn't do anything particularly unusual with particle textures

**Comment by DangerMage** [comment]
Alright. Thanks!
