### ISSUE TITLE
Unexpected packet error/Could not initialize class

### ISSUE THREAD

**Issue by jitterdev** [Earthcomputer/multiconnect#482]
### Latest Version?

- [x] I confirm I have the latest version of multiconnect

### Description

Internal Exception: java.lang.ExceptionInInitializerError (when trying to connect to `play.originrealms.com`)

[Log on first connect](https://mclo.gs/gRIc9Pa) (Threw Unexpected packet error)

[Log on reconnect](https://mclo.gs/QzhIVyr) (Threw java.lang.NoClassDefFoundError: Could not initialize class net.earthcomputer.multiconnect.protocols.generic.TagLoader)

### Log File

https://mclo.gs/gRIc9Pa & https://mclo.gs/QzhIVyr

**Comment by SzczurekYT** [comment]
I also have this when trying to connect to my 1.18.2 smp sever (purpur, fork of paper) from 1.19.2, multiconnect 1.6-beta.23 and viafabric 0.4.9+21-main (and some other mods but I don't think it;s important).

**Comment by YukiAyase** [comment]
QuiltMC/quilted-fabric-api#15
