### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by Egorkagd228** [Earthcomputer/multiconnect#483]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

Multiconnect 1.19.2 Writes that: 
https://user-images.githubusercontent.com/116493408/197390032-dc6d2a22-690f-4574-aedf-af939665a08a.png
Building BetterMC [FABRIC]

### Log File

in game

**Comment by Earthcomputer** [comment]
> in game

No, it's not. There's a reason I ask you to give a log file.
