### ISSUE TITLE
ViaVersion branch doesn't launch

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/multiconnect#485]
To reproduce, on the viaversion branch, either:
- Run `./gradlew runClient`
- Import the project in intellij, and run the "Minecraft Client" run configuration.

You get the following error:
```
java.lang.ClassNotFoundException: net.earthcomputer.multiconnect.impl.via.ViaMulticonnectTranslator
```

From what I understand, `runtimeOnly project(':via-translator')` should have put this on the classpath, but it didn't.

This issue should be fixed within the following constraints:
- No Java code should be changed or moved between subprojects unnecessarily (check with me if unsure).
- The root project should stay as the root project, not be moved to a subproject.
- The root project and the `:via-translator` project have a compile-time dependency on `:translator-api`, and *not* on each other.
- The root project does *not* have a dependency on ViaVersion - only on Minecraft (which needs Loom).
- The `:via-translator` project has a dependency on ViaVersion and Minecraft (which needs Loom).

The reason for the above constraints is mostly legal. ViaVersion is licensed under LGPL and multiconnect under MIT. The `:via-translator` subproject will be licensed to LGPL and not be required to run multiconnect. By contributing to this branch you agree to this licensing.

**Comment by Earthcomputer** [comment]
The bounty for fixing this issue is $20. Normal bounty rules apply. The bounty is payable via PayPal only.

**Comment by wagyourtail** [comment]
> The root project does not have a dependency on ViaVersion

technically it would be transitive earth...

**Comment by Earthcomputer** [comment]
I meant no compile-time dependency :P
