### ISSUE TITLE
[1.19.3] Crash with fabric-api and qsl/quilted-fabric-api

### ISSUE THREAD

**Issue by LostLuma** [Earthcomputer/multiconnect#494]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

Launching the game on 1.19.3 with either fabric-api on fabric, or qsl+quilted-fabric-api on quilt enters a crash-type loop or simply crashes the game.

### Log File

https://files.lostluma.dev/X65cnI.txt fabric
https://files.lostluma.dev/I3VeUW.txt quilt

**Comment by CraftingDragon007** [comment]
I get the same error with the beta version and fabric api
