### ISSUE TITLE
Run within development environment

### ISSUE THREAD

**Issue by haze** [Earthcomputer/multiconnect#5]
Is there any specific steps to running in a development environment?
I assumed it would be as simple as dropping version `1.1.1` in the mods folder (`run/mods`), but connecting to any other versioned server results in [this](https://gist.github.com/12141e2ef3e50a9f28fffcd93d4d75fc) crash.

**Comment by Earthcomputer** [comment]
You are trying to run the release version within the development environment. Do you want to run the mod itself alongside the mod you are developing, or do you only want to depend on the API? I will add relevant instructions in the README.

**Comment by haze** [comment]
I want to run the mod alongside the mod I am developing

**Comment by Earthcomputer** [comment]
How did you add it, did you add it with gradle or directly in your IDE?

**Comment by haze** [comment]
I just dropped the release jar into the mods folder, nothing extra. I am new to using fabric for mod development, so I am unsure if there are any extra steps needed.

**Comment by Earthcomputer** [comment]
I have added a section to the readme, please let me know if it is clear enough :)

**Comment by haze** [comment]
Yep, following the instructions in the README allowed me to launch my mod alongside the multiconnect mod and I was successfully able to connect to a 1.13.1 server.

Thanks again!
