### ISSUE TITLE
Version Button: Cycle Backwards

### ISSUE THREAD

**Issue by leumasme** [Earthcomputer/multiconnect#50]
It takes 15 clicks to cycle the version selector button once, and like an idiot i keep clicking too often, causing me to miss the correct version and have to click through all the versions again.
An idea to make the version switcher button more convenient to use would be to let the user right click it to cycle backwards.
So left clicking while version is auto would cycle forward to 1.12, while right clicking would cycle backwards to 1.15.2

**Comment by Earthcomputer** [comment]
The version button has been changed to a dropdown menu in 1.16
