### ISSUE TITLE
[1.19.3] Crash when opening creative inventory in singleplayer

### ISSUE THREAD

**Issue by Cheos137** [Earthcomputer/multiconnect#505]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

When using multiconnect 1.19.3 1.6-beta.25, the game crashes when opening the creative inventory in singleplayer.
Full modlist + enabled resource packs (including some that alter creative inventory textures) can be found in the attached crash report/logfile.

### Log File

https://gist.github.com/Cheos137/ea0baf293695f03458904d8abf1fe49d#file-latest-log

### Crash Report (if applicable)

https://gist.github.com/Cheos137/ea0baf293695f03458904d8abf1fe49d#file-crash-2022-12-29_12-17-34-client-txt

**Comment by MorningXiao** [comment]
same question

**Comment by PneumaticPiston** [comment]
I as well have had the same issue

**Comment by xtexChooser** [comment]
same

**Comment by AbidHasnineMahi** [comment]
Try removing MiniHUD Mod.

**Comment by xtexChooser** [comment]
no minihud, but Nvidia GTX-750Ti and InventoryHUD

**Comment by JaaiDead** [comment]
its a problem with via verison and multiconnect combined

**Comment by JaaiDead** [comment]
Duplicate of #505
