### ISSUE TITLE
Can someone compile the 1.19.3 version for me

### ISSUE THREAD

**Issue by rbcoder117** [Earthcomputer/multiconnect#515]
Title or can @Earthcomputer make a realse of it also sorry if i sound stupid im not that good with java

**Comment by haykam821** [comment]
Builds of the latest commit are available through [GitHub Actions artifacts](https://github.com/Earthcomputer/multiconnect/suites/9796365117/artifacts/471243998)

**Comment by rbcoder117** [comment]
Tysm
