### ISSUE TITLE
crashes when trying to open inv

### ISSUE THREAD

**Issue by AXDWT** [Earthcomputer/multiconnect#522]
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

the title says at all.

when trying to open inventory minecraft will just freeze a bit and then crashes with the error code -1 

### Log File

https://pastebin.com/S26hgZkS

### Crash Report (if applicable)

https://pastebin.com/iwLa0iRh

**Comment by JaaiDead** [comment]
#505

**Comment by JaaiDead** [comment]
#509

**Comment by NotJacobX** [comment]
Same thing happens to me
