### ISSUE TITLE
Cannot join old server

### ISSUE THREAD

**Issue by Pairman** [Earthcomputer/multiconnect#57]
An error kept me(1.15.2 client) from joining an 1.14.4 server.It occurred after my resourcepacks being changed, idk if this is the reason, so I attach the resourcepacks to this post.
![2020-06-13_16 44 31](https://user-images.githubusercontent.com/18365163/84564833-5242d500-ad97-11ea-966b-ef394472db6d.png)
[Cerulean-Extension-0.0.3beta.zip](https://github.com/Earthcomputer/multiconnect/files/4774333/Cerulean-Extension-0.0.3beta.zip)
[[15-16]DiamondWar0608.zip](https://github.com/Earthcomputer/multiconnect/files/4774334/15-16.DiamondWar0608.zip)

**Comment by Earthcomputer** [comment]
It seems you had a hard crash at some point for some reason, or maybe your internet cut out while connecting. You can fix this error by deleting multiconnect's resource cache. Delete the directory at`.minecraft/config/multiconnect/caches'.

**Comment by Pairman** [comment]
Thanks!
