### ISSUE TITLE
Lag when typing in the direct connect text box

### ISSUE THREAD

**Issue by frctionless** [Earthcomputer/multiconnect#58]
https://streamable.com/9sad7a

**Comment by CDAGaming** [comment]
This is an old version of multiconnect (Or from the master branch thats unmerged from snapshots). The Protocol switching responsible for this lag was rewritten in the snapshots branch for a dropdown system, which among other things, greatly reduced/eliminated the prior lag from typing. I would recommend trying to use the snapshots version if possible and seeing if it provides the same difference.

**Comment by CDAGaming** [comment]
Also removing plausible label as it was indeed noticed by me whilst under the original protocol switching logic

**Comment by frctionless** [comment]
ok

**Comment by Earthcomputer** [comment]
Is this still an issue on the latest version, 1.3?

**Comment by Earthcomputer** [comment]
Confirmed for the latest release, 1.3.2, will get round to fixing this before the next version

**Comment by Earthcomputer** [comment]
Try version 1.3.4
