### ISSUE TITLE
1.12.2 Support (Request)

### ISSUE THREAD

**Issue by CDAGaming** [Earthcomputer/multiconnect#6]
Since 1.12.2 is still a frequently used version, is it in the cards at this time to add 1.12.2 protocol support to this mod.

So far really enjoying it and would love to see it on 1.12.2, if at all possible

**Comment by Earthcomputer** [comment]
Already in the works!

**Comment by CDAGaming** [comment]
Oh dang, Nice!

How far do you plan to end up going with this mod, if I might ask?

(In my opinion 1.12.2 would be a good stopping range though some older versions are still in usage behind 1.12.2)

**Comment by RealIndrit** [comment]
1.8.9 and 1.7.10 if possible, these are VERY popular versions to play with even today, but the simplicity says 1.12.2 is a good stop XD

**Comment by Earthcomputer** [comment]
I'll try and go back step by step as far as I can, I don't see a technical reason why I can't go back even as far as 1.6 or so (I think that's when Minecraft started using Netty). That's my long-term plan, but don't see it as a promise, as life can get in the way of my long-term plans sometimes :p. But for the short term 1.12 is my goal.

**Comment by Earthcomputer** [comment]
See #10
