### ISSUE TITLE
Walls act weird on 1.16.1 (Multiconnect 1.3.3), while connecting to 1.15 server

### ISSUE THREAD

**Issue by azridere** [Earthcomputer/multiconnect#66]
Walls don't connect when connecting to a 1.15 server from 1.16.1.

![maUTgWO](https://user-images.githubusercontent.com/62764868/85954565-631e4980-b946-11ea-9a84-5c6c0abf1c85.png)

**Comment by Earthcomputer** [comment]
Try version 1.3.4
