### ISSUE TITLE
Redstone rending strangely when using 1.16 client on 1.15 server

### ISSUE THREAD

**Issue by SirGavith** [Earthcomputer/multiconnect#68]
Redstone doesn't render quite right when connected to a 1.15 server on a 1.16 client.
It seems like its only rendering half of the wire, on the side that's connected to an adjacent redstone.

Photo of issue: https://user-images.githubusercontent.com/63616979/85960992-4d1b8380-b95c-11ea-84dc-6864b0ce1fb2.png
Similar issue: https://user-images.githubusercontent.com/63616979/85961075-bf8c6380-b95c-11ea-9a0a-13039ae1cea6.png

Expected Behaviour: https://user-images.githubusercontent.com/63616979/85961092-d632ba80-b95c-11ea-93d5-fe79d1145f1e.png

**Comment by Earthcomputer** [comment]
I'm not immediately sure how to fix this issue. It seems to be caused by a change in the vanilla resource pack, causing the old redstone wire states to look like this. I'm not sure how you managed to get into the "similar issue" state though, do you have some steps to reproduce?

**Comment by LeonXu98** [comment]
> I'm not immediately sure how to fix this issue. It seems to be caused by a change in the vanilla resource pack, causing the old redstone wire states to look like this. I'm not sure how you managed to get into the "similar issue" state though, do you have some steps to reproduce?

If you join a legacy version server, when you place a redstone wire, the redstone wire will display as cross and then turn to a dot instantly. Try to right click single redstone wire (dot) in a legacy server will make it display as a cross redstone wire and reverse to dot redstone wire immediately.

**Comment by Earthcomputer** [comment]
I know how to *reproduce* it, I said I'm not immediately sure how to *fix* it. They are very different things.

**Comment by Earthcomputer** [comment]
I have just fixed a related issue with 1.12 servers, and I think that fix would work well for 1.15 too. When we talk about "block connections" in a protocol bridge, we are usually talking about the flattening, but I think the block connections problem applies equally well here, albeit on a smaller scale.

I am planning to rewrite multiconnect's block connector to be multithreaded in the near future, and while I do that, I am hoping to fix this issue.

**Comment by Pairman** [comment]
The bug also occurs when playing 1.14.4 servers with 1.16.5 client. 
Redstone dust in litematica is affected either.

**Comment by Earthcomputer** [comment]
Please update to the latest version, this issue was fixed 8 months ago.
