### ISSUE TITLE
Cats are invisible

### ISSUE THREAD

**Issue by Madis0** [Earthcomputer/multiconnect#69]
1.15.2 server on 1.16.1 client
Multiconnect  1.3.3
Fabric API 0.13.1 b 370

**Comment by Earthcomputer** [comment]
Cannot reproduce. Do you have any other mods?
![2020-07-05_11 32 39](https://user-images.githubusercontent.com/13084089/86530754-691aaa00-beb3-11ea-8857-e0522e1c017e.png)

**Comment by Madis0** [comment]
The server I tested with upgraded, so I'll reopen when I can reproduce it again.

But yes, I have other mods, I suspect Sodium or Lithium, didn't test without though yet. And no, I don't think there is something special about them, other than being tamed.

**Comment by nogutsnoglory69** [comment]
just did some testing. it's lithium that's the culprit, remove it from your mods folder and cats and wolves are visible again.

**Comment by Earthcomputer** [comment]
I am working on compatibility with lithium and sodium. Would you mind figuring out exactly which lithium setting is the culprit? You might get some help in jellysquid's discord for that.

**Comment by nogutsnoglory69** [comment]
Found it. It's this one: mixin.entity.data_tracker.use_arrays

**Comment by Earthcomputer** [comment]
I'm surprised it didn't crash, as it has done in the past. See this issue: https://github.com/Earthcomputer/multiconnect/issues/21
