### ISSUE TITLE
Found some mayor bug that are hard to explain in detail here, there are alot of them XD

### ISSUE THREAD

**Issue by RealIndrit** [Earthcomputer/multiconnect#7]
Please drop your discord, so me and CDAGaming can reach out with some bugs that can and will caus a lot problems in the future for users :/ 

Btw, your mod is amazing anyways (when ids arent funky and crashes my game)

**Comment by Earthcomputer** [comment]
Since so many people ask me for discord, I have created a discord account, Earthcomputer#2690. However, this is far from the best way to contact me, it's easier to keep track of issues here. But right now I am logged in to discord so you can message me there.

**Comment by Earthcomputer** [comment]
Multiple issues were observed, many of which were incompatibilities. However one major issue was uncovered, see #8.
