### ISSUE TITLE
Stonecutter and cartography table have wrong gui

### ISSUE THREAD

**Issue by nogutsnoglory69** [Earthcomputer/multiconnect#72]
I'm using multiconnect 1.3.3 on a 1.15.2 server and both of these blocks have the wrong gui when you open them. The stonecutter has the cartography table ui, the cartography table has the furnace ui. 
![2020-07-05_04 06 47](https://user-images.githubusercontent.com/53264835/86524023-584b4380-be75-11ea-932d-2e0ec2ba3377.png)
![2020-07-05_04 06 53](https://user-images.githubusercontent.com/53264835/86524024-597c7080-be75-11ea-8594-15976d795096.png)

**Comment by Earthcomputer** [comment]
Thanks for reporting!

**Comment by Earthcomputer** [comment]
Try version 1.3.4
