### ISSUE TITLE
Both Install WorldEdit and MultiConnect Makes You Can't Join a Local Game

### ISSUE THREAD

**Issue by LeonXu98** [Earthcomputer/multiconnect#76]
# Environment
## Fabric Loader Version: 
0.8.9 build 203
## Mods:
* WorldEdit 7.2.0-SNAPSHOT-5148-50a744f（7.2.0 beta 2 can reproduce this issue also）
* ModMenu 1.12.2 build 7
* MultiConnect 1.3.5
* FabricAPI 0.14.1 build 372
# How to reproduce This Issue
1. Install Mods in this list and start game
2. Create a new world and join the local game
    * You will found the game will freeze when the progress reach 100%
    * The size of region files keeps 0 bytes
    * If you join a pre-created local world, the game will freeze when the progress reach 100%
* You can still join a multi-player game normally when mod in this list is installed.

**Comment by Earthcomputer** [comment]
Fixed, the fix will be released with the new 1.16.2 version.
