### ISSUE TITLE
1.12.2 Terrain

### ISSUE THREAD

**Issue by Lasagnenator** [Earthcomputer/multiconnect#78]
### Info
- Server: us.shotbow.net (BungeeCord-Spigot server)
- MC version: 1.16.1
- Fabric version: fabric-loader-0.8.8+build.202-1.16.1
- Java version: 14.0.1 64bit AdoptOpenJDK
- Reported error on screen: `NullPointerException : null @ net.md_5.bungee.chat.TextComponentSerializer:24`
I think this error simply the server's end for something bungeecord related as the world seems to load for a split second before the error screen shows up. It works on 1.12.2 vanilla though.
- Error in log files is `java.lang.RuntimeException: Received invalid biome id: 255` spammed a lot. (log file also attached). When connecting with vanilla 1.12.2 the f3 biome reported is plains.
- It also takes a really long time to generate the error. The 'Joining world' can be seen and then it hangs for a while eating the cpu before displaying the error.
### Any other mods?
- Tested with multiconnect 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2 on their own. All failed with same error screens and same log errors. (Have not tested any other versions)
- Interesting case: When I load all of my mods (**multiconnect-1.3.4**, brandpacket-0.0.1, g4mespeed-1.0.6, litematica-fabric-1.16.1-0.0.0-dev.20200704.012053, malilib-fabric-1.16.1-0.10.0-dev.21+arne.1, minihud-fabric-1.16.1-0.19.0-dev.20200701.005153, Phosphor-0.6.0, Sodium ([this source](https://github.com/jellysquid3/sodium-fabric/commit/ca8902c44af03284d5fea759498aac8535ad49f1)), voyager-1.0.0), it does not hang. It fails to load the terrain but entities are visible moving about. If I try using 1.3.6 it doesn't even get to there (Have not tested any other combinations of versions). 
- (Multiconnect 1.3.4) It appears that Sodium is the reason that I am able to get past the error screen. Disabling Sodium gives the error again.
![2020-07-10_19 45 45](https://user-images.githubusercontent.com/38394321/87143441-6c65c980-c2e9-11ea-9ae7-b9350856c7fb.png)
![2020-07-10_20 16 43](https://user-images.githubusercontent.com/38394321/87143941-4e4c9900-c2ea-11ea-81f6-579aafcd0615.png)
- I remember using multiconnect perfectly with this particular server before... I'll keep looking into different configurations to try to find the working one. Might have been 1.15.2.
### What about other servers?
- Tried connecting to 2b2t.org, I left the computer running for a few hours then when I joined, no terrain showed up. Same errors in the logs. Entities showed up (skeleton horses were all I could see). I cannot say for sure whether multiconnect caused the terrain failure as I was using the same list of mods above. I am _not_ going to wait again for that blasted queue to test it out.
### Log file
Log file for multiconnect 1.3.6: [latest.log](https://github.com/Earthcomputer/multiconnect/files/4901805/latest.log).

**Comment by Earthcomputer** [comment]
Just fyi, multiconnect 1.3.4 was incompatible with sodium and caused blocks not to load, which is fixed in the latest version of multiconnect (#70), so that part of the report is invalid.

I have no idea why this server is sending biome ID 255, which is not a valid biome ID. I could turn that error into a warning and default to plains or something.

**Comment by Lasagnenator** [comment]
Well the reason I put that interesting case is because it worked better in 1.3.4 than it did in 1.3.6 or 1.3.5. When Sodium was not loaded, the game would hang and then display the error screen. However, if I used Sodium + 1.3.4 I would join the game (despite terrain not loading). Using 1.3.6 or 1.3.5 with Sodium would result in the error screen.

**Comment by Earthcomputer** [comment]
@Lasagnenator is this still a concern in the latest version of multiconnect, 1.3.8?

**Comment by Earthcomputer** [comment]
I don't think these issues would be reproducible anymore on the current version. If they are, please reply and I can reopen this issue.
