### ISSUE TITLE
Player Head Textures Are Not Converted Properly on 1.16+ Clients

### ISSUE THREAD

**Issue by amnotbananaama** [Earthcomputer/multiconnect#79]
![](https://i.imgur.com/5fWGZMD.png)

**Analysis**
My guess is that Multiconnect is not handling the changeover from string UUIDs to the current int-array format that occured in 1.16 snapshots. As a result, the (improper) old UUID format is sent to the client, which it fails to render.

See https://minecraft.gamepedia.com/UUID for relevant information.

**Comment by Earthcomputer** [comment]
Relates to the more general problem of block entity translation, thanks for reporting!

**Comment by Earthcomputer** [comment]
Fixed, in the next release, multiconnect will apply vanilla's datafixers to block entities such as skulls.
