### ISSUE TITLE
Won't 1.16 cause issues

### ISSUE THREAD

**Issue by Bzyli** [Earthcomputer/multiconnect#80]
Hello, I was planning to develop an Minecraft client that can connect to multiple version using multiconnect but one of my friends told me that putting 1.16 support would cause false positive detection by anticheats, what do you think about it ?

Thanks for the awesome work your doing!
Bzyli

**Comment by Earthcomputer** [comment]
The only anti-cheat I know of which is good enough to detect this is hypixel, which makes their own anti-cheat software. Multiconnect previously had this problem, however now hypixel is special-cased by multiconnect to always connect with the real client version, which makes the client indistinguishable from vanilla. I have never seen any anti-cheat issues on other servers, if you find any please let me know. As always, use these mods at your own risk.

**Comment by Bzyli** [comment]
Ok, thank you for the answer, have a nice day
