### ISSUE TITLE
Version Button is gone.

### ISSUE THREAD

**Issue by L0um15** [Earthcomputer/multiconnect#83]
Clean installation of minecraft with fabric mod loader makes "Version button" not displaying at least for me. 

Using: 
   - Fabric 0.9.0+build.204-1.16.1
   - Lithium 0.5.1
   - Phosphor 0.6.0
   - Sodium 0.1.0
   - VoxelMap 1.10.4
   - ModMenu1.14.5
   - clientcommands 2.4.1
   - Inventory Profiles 0.4.2.

Tested every mod combo with or without FabricAPI 0.15.1.

Button was displaying properly with latest version of Aristois and same mods (i just copied them).

Java Version: Built in launcher (used)/ JDK 11.0.7

Log files:
[launcher_log.txt](https://github.com/Earthcomputer/multiconnect/files/4968611/launcher_log.txt)

[latest.log](https://github.com/Earthcomputer/multiconnect/files/4968613/latest.log)

Photos:
![Adnotacja 2020-07-23 221406](https://user-images.githubusercontent.com/44427021/88335288-587f8600-cd33-11ea-81f8-69f5bc060bbd.jpg)

![InkedAdnotacja 2020-07-23 221426_LI](https://user-images.githubusercontent.com/44427021/88335877-4eaa5280-cd34-11ea-8c07-4d6fee80a1db.jpg)

**Comment by Earthcomputer** [comment]
That version button is added by CDAGaming's fork and is not in the official version of multiconnect. Usually you are supposed to rely on multiconnect's smart auto version detector, and if that fails you can press edit server and edit the version of that specific server manually.

**Comment by CDAGaming** [comment]
The Global Versions button is only available in my fork of multiconnect, otherwise you can find it in the Edit or Direct Connections screen
