### ISSUE TITLE
Opening "Edit Server", "Direct Connect" or "Add Server" causes extreme lag spike.

### ISSUE THREAD

**Issue by CalXee** [Earthcomputer/multiconnect#85]
It is extremely laggy and annoying to open those. It takes about 5-10 seconds for me.

**Comment by Earthcomputer** [comment]
What multiconnect version are you on?

**Comment by CalXee** [comment]
I am on the latest version. 1.3.7

**Comment by Earthcomputer** [comment]
I believe it's caused by doing a DNS lookup on every server in your saved server version list. I'll see what I can do to optimize it

**Comment by CalXee** [comment]
I indeed do have a wide variety of servers using different versions like Hypixel and PvPLegacy.

**Comment by Earthcomputer** [comment]
Should be fixed in the latest release.
