### ISSUE TITLE
How to use the api.

### ISSUE THREAD

**Issue by cristiioan** [Earthcomputer/multiconnect#86]
I want to make a client in fabric and I need this future inside the client

**Comment by Earthcomputer** [comment]
I don't support hacked clients. If you're not making a hacked client, then I can help. Every method and class in the API is documented, do you have any specific questions?

**Comment by cristiioan** [comment]
I need to add it as as a mod without the player to download it.

**Comment by Earthcomputer** [comment]
Just the API or the full mod? If your mod wants to use the API, then you can include the API without the mod.

**Comment by cristiioan** [comment]
I need the mod for now.

**Comment by Earthcomputer** [comment]
I would rather you downloaded the mod at runtime so it doesn't affect my download stats. The mod is published on my maven repository: https://bintray.com/earthcomputer/mods/multiconnect

**Comment by cristiioan** [comment]
And autodownload the last version so I don't have to change the verison when you relase a new version.

**Comment by Earthcomputer** [comment]
https://dl.bintray.com/earthcomputer/mods/net/earthcomputer/multiconnect/:maven-metadata.xml

**Comment by Username404-59** [comment]
://docs.gradle.org/current/userguide/dependency_verification.html

**Comment by Username404-59** [comment]
> I want to make a client in fabric and I need this future inside the client
uh how are you going to make your wurst fork compatible with fabric mods?

**Comment by Earthcomputer** [comment]
Please don't talk about hacked clients here.

**Comment by Username404-59** [comment]
Okay okay i was just wondering, he could make a mod instead of a hacked client...

**Comment by cristiioan** [comment]
@Earthcomputer Gradle can't find project.

**Comment by Earthcomputer** [comment]
@cristiioan please show the full error

**Comment by cristiioan** [comment]
* What went wrong:
A problem occurred configuring root project 'LionClient'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find net.earthcomputer.multiconnect:1.3.8:.
     Searched in the following locations:
       - file:/C:/Users/ioanm/Desktop/LionClient/build/loom-cache/1.3.8.jar
       - file:/C:/Users/ioanm/Desktop/LionClient/.gradle/loom-cache/remapped_mods/1.3.8.jar
       - file:/C:/Users/ioanm/.gradle/caches/fabric-loom/1.16.1-mapped-net.fabricmc.yarn-1.16.1+build.1-v2/1.3.8.jar
     Required by:
         project

**Comment by cristiioan** [comment]
`plugins {
	id 'fabric-loom' version '0.4-SNAPSHOT'
	id 'maven-publish'
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

minecraft {
}
repositories {
	maven {
		url 'https://dl.bintray.com/earthcomputer/mods'
	}
}
dependencies {
	//to change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modCompile "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modCompile "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modRuntime 'net.earthcomputer:multiconnect:1.3.8'
	modImplementation 'net.earthcomputer.multiconnect:1.3.8'
	// net.wurstclient.ai.PathPos extends net.minecraft.util.math.BlockPos,
	// which uses javax.annotation.concurrent.Immutable, which is part of
	// the JSR305 library.
	//
	// In other words, Wurst won't compile without this library,
	// even though it's Minecraft that actually uses it.
	modCompile 'com.google.code.findbugs:jsr305:3.0.2'

	// PSA: Some older mods, compiled on Loom 0.2.1, might have outdated Maven POMs.
	// You may need to force-disable transitiveness on them.
}

processResources {
	inputs.property "version", project.version

	from(sourceSets.main.resources.srcDirs) {
		include "fabric.mod.json"
		expand "version": project.version
	}

	from(sourceSets.main.resources.srcDirs) {
		exclude "fabric.mod.json"
	}
}

// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
	options.encoding = "UTF-8"
}

// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
// if it is present.
// If you remove this task, sources will not be generated.
task sourcesJar(type: Jar, dependsOn: classes) {
	classifier = "sources"
	from sourceSets.main.allSource
}

jar {
	from "LICENSE"
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			// add all the jars that should be included when publishing to maven
			artifact(jar) {
				builtBy remapJar
			}
			artifact(sourcesJar) {
				builtBy remapSourcesJar
			}
		}
	}

	// select the repositories you want to publish to
	repositories {
		// uncomment to publish to the local maven
		// mavenLocal()
	}
}`

**Comment by Earthcomputer** [comment]
`net.earthcomputer:multiconnect:1.3.8`.

Learn maven.

**Comment by Earthcomputer** [comment]
Also don't develop hacked clients.
