### ISSUE TITLE
Game freezes upon switching from singleplayer to any 3rd-party server.

### ISSUE THREAD

**Issue by Kichura** [Earthcomputer/multiconnect#87]
When multiconnect-1.3.8 is used to connect to any singleplayer world -> Wandering around for a while until all chunks around player are loaded in place,

Leaving the singleplayer world and then trying to switch to a 3rd-party server freezes the entire game with no logs found in latest.log files.

**Comment by Earthcomputer** [comment]
I'm sure this is a regression but I can't find the original issue...

**Comment by Earthcomputer** [comment]
Fixed, the fix will be released with the new 1.16.2 version.
