### ISSUE TITLE
Failed to connect to the server

### ISSUE THREAD

**Issue by WKyouka** [Earthcomputer/multiconnect#89]
com.google.gson.jsonsyntaxexception:com.google.gson.stream.malformedjsonexception:unterminated string at line 1 column 48684 path $.versions[211].null

**Comment by Earthcomputer** [comment]
It seems you had a hard crash at some point for some reason, or maybe your internet cut out while connecting. You can fix this error by deleting multiconnect's translation cache. Delete the directory at `.minecraft/config/multiconnect/caches`.
