### ISSUE TITLE
Banner Layer Regression

### ISSUE THREAD

**Issue by CDAGaming** [Earthcomputer/multiconnect#90]
Today: https://cdn.discordapp.com/attachments/658063802780221452/747944015265136740/Screenshot_from_2020-08-25_17-22-05.png

January 2020: https://cdn.discordapp.com/attachments/529059123246006285/665032749303726090/unknown.png

Seemingly the orange layer for Banners has become missing again after today's changes

**Comment by Earthcomputer** [comment]
Can you compile from the latest commit and see if the issue is fixed?

**Comment by CDAGaming** [comment]
Forgot to respond in record, but yes it was resolved

**Comment by Earthcomputer** [comment]
No need to lock it lol, that's only if someone is spamming or something
