### ISSUE TITLE
Can't load into single player if cancel connect to server

### ISSUE THREAD

**Issue by R3alCl0ud** [Earthcomputer/multiconnect#91]
If you cancel connecting to a server that is on minecraft version 1.15.2 or older and then try to load into a single player world you are met with the 'Bad Datapack error' as shown in the screen shot. Clicking the safe mode button does nothing.
![image](https://user-images.githubusercontent.com/6125664/91350785-09969780-e79c-11ea-8e36-d4758250c865.png)

I've attached the stack trace below in the stacktrace.txt file
[stacktrace.txt](https://github.com/Earthcomputer/multiconnect/files/5132574/stacktrace.txt)

Steps to reproduce:

1. Set connect version to 1.15.2 or lower
2. Click the cancel button before you finish connecting to the server
3. Load a singleplayer world

Notes:
Issue persists until you
1. Restart the client
2. Let the game actually finish connecting to a server

**Comment by Earthcomputer** [comment]
Has this been resolved as of the latest version of multiconnect, 1.3.30?

**Comment by Earthcomputer** [comment]
Probably resolved, due to a lack of anyone responding.
