### ISSUE TITLE
Block Textures Are Very Odd (1.15-1.16.2)

### ISSUE THREAD

**Issue by shadowtigercool** [Earthcomputer/multiconnect#94]
![Screenshot_13](https://user-images.githubusercontent.com/36507966/91661858-8f705680-eaac-11ea-812a-7757ac127b16.png)
Colored, Wrong Texture On Some Blocks.

**Comment by shadowtigercool** [comment]
Glass Panes Are Also The Wrong Color
![Screenshot_14](https://user-images.githubusercontent.com/36507966/91661893-d65e4c00-eaac-11ea-8e4e-994189db00ed.png)

**Comment by shadowtigercool** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/36507966/91661919-060d5400-eaad-11ea-8fc6-d27ea6cfab84.png)
![Screenshot_16](https://user-images.githubusercontent.com/36507966/91661928-1a515100-eaad-11ea-9f05-5275e619092a.png)

**Comment by shadowtigercool** [comment]
And It's Not The Resource Pack, IDK if it's another Mod Doing it.

**Comment by Earthcomputer** [comment]
Please send your mod list then

**Comment by shadowtigercool** [comment]
![Screenshot_17](https://user-images.githubusercontent.com/36507966/91662479-aa44ca00-eab0-11ea-821f-053da140d9ad.png)

**Comment by shadowtigercool** [comment]
![Screenshot_18](https://user-images.githubusercontent.com/36507966/91662508-e37d3a00-eab0-11ea-957c-08c48b54806b.png)

**Comment by Earthcomputer** [comment]
OptiFine may cause visual artifacts with multiconnect. Please install one or more of the various [OptiFine alternatives](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754) (which are better than OptiFine) instead.
