### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by sourTaste000** [Earthcomputer/multiconnect#96]
Describe Issue:
Just crashes when you join the server.

Log is here:
https://paste.ee/p/SOBdH

**Comment by sourTaste000** [comment]
cannot reproduce issue again

**Comment by sourTaste000** [comment]
signs are invisible tho

**Comment by sourTaste000** [comment]
![image](https://user-images.githubusercontent.com/47074495/92046434-61eb0d80-ed37-11ea-9b5c-c52706656e2c.png)

**Comment by Earthcomputer** [comment]
@sourTaste000 please create a separate bug report for that.
