### ISSUE TITLE
Chests become invisible via 1.16.3 on a 1.15.2 server.

### ISSUE THREAD

**Issue by Kichura** [Earthcomputer/multiconnect#98]
When playing on a 1.15.2 server that has either single or double chests nearby at player, They are invisible until a right click is performed to force a rendering on them.

Additional note: They will become invisible again when out of sight and then coming back.

**Comment by Earthcomputer** [comment]
Which server?

**Comment by Kichura** [comment]
play.mystiamc.com - 1.15.2 earth server, This is where it has been tested at.

**Comment by Kichura** [comment]
![image](https://user-images.githubusercontent.com/68134602/93004786-a1d99e00-f54a-11ea-83df-a8a3baadb2a2.png)
Picture of invisible chest in case it didn't work the first time.

**Comment by Earthcomputer** [comment]
Cannot reproduce
![Screenshot from 2020-09-12 22-02-42](https://user-images.githubusercontent.com/13084089/93004916-b6666800-f543-11ea-945d-3f8d7d4b4b32.png)

**Comment by Earthcomputer** [comment]
What mods do you have installed?

**Comment by Kichura** [comment]
![image](https://user-images.githubusercontent.com/68134602/93004933-46101480-f54c-11ea-8527-8ddeb82ae8f5.png)
(Fabric-MoveChat is Chat Up! and Fabric-capes is just minecraftcapes from james)

**Comment by Earthcomputer** [comment]
Item Model Fix looks suspicious, let me check with that

**Comment by Kichura** [comment]
https://www.curseforge.com/minecraft/mc-mods/item-model-fix - URL for it.

**Comment by Earthcomputer** [comment]
Ok it's not that. I'm not sure what it could be then, do you think you could find which mod it's incompatible with?

**Comment by Kichura** [comment]
I will try to inspect one of the mods and see if one of them is compromised.

**Comment by Kichura** [comment]
Tested so far:

MultiConnect only: Runs OK,
MultiConnect with Fabric-API: Runs OK,
MultiConnect with Sodium: Crashes client entirely when visiting 1.15.2 servers on 1.16.3 (Perhaps this is the culprit?),
MultiConnect with XLPackets: Runs OK,
MultiConnect with Phosphor: Runs OK,
MultiConnect with Lithium: Runs OK,
MultiConnect with BrandPacket: Runs OK,
MultiConnect with DeBrand: Runs OK,
MultiConnect with "Fabric-Capes": Runs OK,
MultiConnect with OK Zoomer: Runs OK.

Conclusion: I am likely that sodium is causing problems since all mods combined run sodium fine but chests may render invisible but with multiconnect & sodium only, game crashes entirely.

**Comment by Earthcomputer** [comment]
Is Sodium even updated to 1.16.3? O_o

**Comment by Kichura** [comment]
https://github.com/FlashyReese/sodium-fabric/tree/1.16.2/dev - Sodium i used, But i don't think this is the perfect decision for "finalized" sodium. + This appears to be compatible with 1.16.3 but i cannot confirm this with other machines.

**Comment by Earthcomputer** [comment]
I just installed that version of Sodium and it rendered fine.

**Comment by Kichura** [comment]
Tried with the combined mods then and the issue is back. (This time i set a home to a random location then warped to it then instantly back to tokyo place)

**Comment by Kichura** [comment]
https://streamable.com/5s41yl - Clip of me teleporting rapidly.

**Comment by Earthcomputer** [comment]
If you can find a minimal combination of mods that it happens with that would be great.

**Comment by Kichura** [comment]
^ Tried this test: Combining multiconnect with sodium and lithium as in minimal combination appear to cause this problem on my client-side.

**Comment by Kichura** [comment]
Found out the solution: Lithium-0.5.5 (SNAPSHOT) with FlashyReese's Sodium caused the issue to reproduce, In short the lithium version had to be rolled back to 0.5.4 to avoid this problem.
